# Generated by Django 5.2.9 on 2026-01-12 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the article was viewed')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='Session ID for tracking user sessions', max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent string', max_length=500)),
                ('referrer', models.URLField(blank=True, default='', help_text='Referrer URL')),
            ],
            options={
                'verbose_name': 'Article View',
                'verbose_name_plural': 'Article Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique conversation ID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('abandoned', 'Abandoned')], db_index=True, default='active', help_text='Current status of the conversation', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the conversation started')),
                ('last_message_at', models.DateTimeField(auto_now=True, help_text='When the last message was sent')),
                ('page_url', models.URLField(blank=True, default='', help_text='Page URL where conversation was started', max_length=2000)),
                ('product_context', models.JSONField(blank=True, default=dict, help_text='SDK ProductContext snapshot at conversation start')),
                ('escalation_reason', models.CharField(blank=True, default='', help_text='Reason for escalation if escalated', max_length=255)),
                ('escalated_to', models.CharField(blank=True, default='', help_text='Destination of escalation (intercom, zendesk, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique message ID', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, help_text='Who sent this message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the message was sent')),
                ('chunks_retrieved', models.JSONField(blank=True, default=list, help_text='List of chunks retrieved for this response: [{chunk_id, score, source_article_id}]')),
                ('model_used', models.CharField(blank=True, default='', help_text='LLM model used to generate response (e.g., gpt-4o, claude-3-5-sonnet)', max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Response generation latency in milliseconds', null=True)),
                ('feedback', models.CharField(choices=[('none', 'No Feedback'), ('up', 'Helpful'), ('down', 'Not Helpful')], db_index=True, default='none', help_text='User feedback on this response', max_length=10)),
                ('feedback_comment', models.TextField(blank=True, default='', help_text='Optional comment with feedback')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContentGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.CharField(db_index=True, help_text='The unanswered query', max_length=500)),
                ('frequency', models.IntegerField(default=1, help_text='How many times this query was asked')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this gap was first detected')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this gap was last seen')),
                ('status', models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed'), ('dismissed', 'Dismissed')], db_index=True, default='open', help_text='Current gap status', max_length=20)),
            ],
            options={
                'verbose_name': 'Content Gap',
                'verbose_name_plural': 'Content Gaps',
                'ordering': ['-frequency', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, help_text='Search query text', max_length=500)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the search was performed')),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='Session ID for tracking user sessions', max_length=255)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.CharField(db_index=True, help_text='Persistent visitor ID from SDK (stored in localStorage)', max_length=64)),
                ('session_id', models.CharField(db_index=True, help_text='Session ID from SDK (stored in sessionStorage)', max_length=64, unique=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', help_text="Customer's authenticated user ID (passed via SDK config)", max_length=255)),
                ('user_profile', models.JSONField(blank=True, default=dict, help_text='User profile data from SDK UserProfile')),
                ('first_page_url', models.URLField(blank=True, default='', help_text='First page URL where the session started', max_length=2000)),
                ('last_page_url', models.URLField(blank=True, default='', help_text='Last page URL seen in this session', max_length=2000)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent string', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the session started')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last activity in this session')),
                ('page_count', models.PositiveIntegerField(default=1, help_text='Number of unique pages visited in this session')),
                ('chat_count', models.PositiveIntegerField(default=0, help_text='Number of chat conversations started in this session')),
                ('search_count', models.PositiveIntegerField(default=0, help_text='Number of searches performed in this session')),
            ],
            options={
                'verbose_name': 'Widget Session',
                'verbose_name_plural': 'Widget Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
