# Generated by Django 5.2.9 on 2026-01-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('knowledge', '0001_initial'),  # Changed from content to knowledge
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='knowledge_item',
            field=models.ForeignKey(help_text='Knowledge item that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='knowledge.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='organization',
            field=models.ForeignKey(help_text='Organization this view belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='users.organization'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='organization',
            field=models.ForeignKey(help_text='Organization this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='users.organization'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.chatconversation'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='organization',
            field=models.ForeignKey(help_text='Organization this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='users.organization'),
        ),
        migrations.AddField(
            model_name='contentgap',
            name='organization',
            field=models.ForeignKey(help_text='Organization this gap belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='content_gaps', to='users.organization'),
        ),
        migrations.AddField(
            model_name='contentgap',
            name='suggested_knowledge_item',
            field=models.ForeignKey(blank=True, db_column='suggested_article_id', help_text='Knowledge item created to address this gap (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_content_gaps', to='knowledge.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='search',
            name='clicked_knowledge_item',
            field=models.ForeignKey(blank=True, db_column='clicked_article_id', help_text='Knowledge item that was clicked (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_search_clicks', to='knowledge.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='search',
            name='organization',
            field=models.ForeignKey(help_text='Organization this search belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='users.organization'),
        ),
        migrations.AddField(
            model_name='widgetsession',
            name='organization',
            field=models.ForeignKey(help_text='Organization this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='widget_sessions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Widget session this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='analytics.widgetsession'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['organization', 'knowledge_item', '-viewed_at'], name='analytics_a_organiz_902676_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['knowledge_item', '-viewed_at'], name='analytics_a_knowled_ce7603_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['session_id', '-viewed_at'], name='analytics_a_session_8b3d17_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='analytics_c_convers_ac119d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['organization', '-timestamp'], name='analytics_c_organiz_7c14de_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', '-timestamp'], name='analytics_c_role_1cdc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['feedback', '-timestamp'], name='analytics_c_feedbac_6a062b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgap',
            index=models.Index(fields=['organization', 'status', '-frequency'], name='analytics_c_organiz_1db823_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgap',
            index=models.Index(fields=['status', '-frequency'], name='analytics_c_status_8fadae_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['organization', '-searched_at'], name='analytics_s_organiz_3ec7be_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['query', '-searched_at'], name='analytics_s_query_6054b8_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['session_id', '-searched_at'], name='analytics_s_session_eaaa77_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetsession',
            index=models.Index(fields=['organization', 'visitor_id'], name='analytics_w_organiz_2caae8_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetsession',
            index=models.Index(fields=['organization', '-started_at'], name='analytics_w_organiz_2ee384_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetsession',
            index=models.Index(fields=['visitor_id', '-started_at'], name='analytics_w_visitor_1ca1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['organization', '-started_at'], name='analytics_c_organiz_24e9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['organization', 'status'], name='analytics_c_organiz_e6ae77_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session', '-started_at'], name='analytics_c_session_b98352_idx'),
        ),
    ]
