# Generated by Django 5.2.9 on 2026-01-12 22:53
# Modified to use knowledge.KnowledgeItem instead of help_center.HelpArticle

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('knowledge', '0001_initial'),  # Changed from help_center to knowledge
    ]

    operations = [
        # These migrations are now handled by 0002_initial which references knowledge.knowledgeitem
        # Keeping as no-ops for migration history compatibility
    ]
