# Generated by Django 5.2.9 on 2026-01-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_articleview_article_and_more'),
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='organization',
            field=models.ForeignKey(help_text='Organization this view belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_article_views', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='organization',
            field=models.ForeignKey(help_text='Organization this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_chat_conversations', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='organization',
            field=models.ForeignKey(help_text='Organization this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_chat_messages', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='contentgap',
            name='organization',
            field=models.ForeignKey(help_text='Organization this gap belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_content_gaps', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='search',
            name='organization',
            field=models.ForeignKey(help_text='Organization this search belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_searches', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='widgetsession',
            name='organization',
            field=models.ForeignKey(help_text='Organization this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_widget_sessions', to='users.organization'),
        ),
    ]
