# Generated by Django 5.2.9 on 2026-01-13 05:33
# Modified: Use conditional SQL to handle both fresh and existing databases
#
# For existing databases:
#   - DB might have analytics_a_article_ce7603_idx (old field name 'article')
#   - Need to rename to analytics_a_knowled_1126ee_idx
#
# For fresh databases (CI):
#   - DB has analytics_a_knowled_ce7603_idx (created correctly in 0002)
#   - No rename needed, just update Django state

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename old index name to new name only if old name exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check if the old 'article' index exists (legacy from before field rename)
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'analytics_a_article_ce7603_idx'
            )
        """)
        old_article_index_exists = cursor.fetchone()[0]
        
        if old_article_index_exists:
            # Existing database with old index - rename it
            cursor.execute("""
                ALTER INDEX "analytics_a_article_ce7603_idx" 
                RENAME TO "analytics_a_knowled_ce7603_idx"
            """)


def noop(apps, schema_editor):
    """Reverse operation - no-op since we can't know the original state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_articleview_organization_and_more"),
    ]

    operations = [
        # The first RenameIndex is removed since the index name in 0002 is correct
        # Just run a Python function to conditionally rename the legacy index
        migrations.RunPython(rename_index_if_exists, noop),
    ]
