# Generated by Django 5.2.9 on 2026-01-13 19:25
# Modified: Use conditional SQL to handle cases where indexes don't exist

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check and rename first index
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'analytics_a_organiz_902676_idx'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                ALTER INDEX "analytics_a_organiz_902676_idx" 
                RENAME TO "analytics_a_organiz_02c3a4_idx"
            """)
        
        # Check and rename second index
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'analytics_a_knowled_ce7603_idx'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                ALTER INDEX "analytics_a_knowled_ce7603_idx" 
                RENAME TO "analytics_a_knowled_1126ee_idx"
            """)


def noop(apps, schema_editor):
    """Reverse operation - no-op since we can't know the original state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0005_rename_analytics_a_organiz_902676_idx_analytics_a_organiz_02c3a4_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, noop),
    ]
