# Generated by Django 5.2.9 on 2026-01-13 21:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0006_rename_analytics_a_organiz_902676_idx_analytics_a_organiz_02c3a4_idx_and_more",
        ),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryCluster",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique cluster ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canonical_query",
                    models.TextField(help_text="Representative query for this cluster"),
                ),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Embedding vector of the canonical query",
                        null=True,
                    ),
                ),
                (
                    "query_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Number of queries in this cluster",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the first query in this cluster was seen",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When the most recent query in this cluster was seen",
                    ),
                ),
                (
                    "avg_feedback_score",
                    models.FloatField(
                        blank=True,
                        help_text="Average feedback score for responses (-1 to 1, where 1 is all positive)",
                        null=True,
                    ),
                ),
                (
                    "resolution_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of conversations resolved without escalation (0-1)",
                        null=True,
                    ),
                ),
                (
                    "is_content_gap",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this cluster represents a content gap (high volume, low satisfaction)",
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Manual or auto-generated labels for this cluster",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Category for this cluster (product, support, billing, etc.)",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Cluster",
                "verbose_name_plural": "Query Clusters",
                "ordering": ["-query_count"],
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="external_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="External session identifier string (from widget)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Client IP address", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="logging_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this conversation appears in analytics (False for testing)",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata for extensibility",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="referer",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Referer URL where user came from",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True,
                help_text="Full-text search vector for conversation content",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Conversation title, auto-generated from first query",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="user_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client user agent string",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="cluster_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score of primary cluster match (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="feedback_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When user provided feedback", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="intent_category",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Classified intent (product, support, documentation, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="intent_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score for intent classification (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="query_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="MD5 hash of query for deduplication/clustering",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="query_type",
            field=models.CharField(
                choices=[
                    ("ask", "Ask (Conversational)"),
                    ("search", "Search (Keyword/Semantic)"),
                ],
                db_index=True,
                default="ask",
                help_text="Type of query: ask (conversational) or search",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reasoning_trace",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="ReAct agent reasoning steps: [{thought, action, observation}]",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tokens_generated",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tokens generated before stop (if stopped early)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="was_stopped",
            field=models.BooleanField(
                default=False, help_text="Whether user stopped streaming early"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["external_session_id"], name="analytics_c_externa_009438_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["logging_enabled", "-started_at"],
                name="analytics_c_logging_35bad9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="analytics_c_search__75859e_gin"
            ),
        ),
        migrations.AddField(
            model_name="querycluster",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this cluster belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_clusters",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="primary_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary cluster this query belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="analytics.querycluster",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["query_type", "-timestamp"],
                name="analytics_c_query_t_bac830_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["query_hash"], name="analytics_c_query_h_3794d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["intent_category", "-timestamp"],
                name="analytics_c_intent__20a91e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["primary_cluster", "-timestamp"],
                name="analytics_c_primary_2107fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="querycluster",
            index=models.Index(
                fields=["organization", "-query_count"],
                name="analytics_q_organiz_f1e841_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="querycluster",
            index=models.Index(
                fields=["organization", "-last_seen_at"],
                name="analytics_q_organiz_80703b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="querycluster",
            index=models.Index(
                fields=["organization", "is_content_gap"],
                name="analytics_q_organiz_f38b27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="querycluster",
            index=models.Index(
                fields=["organization", "category"],
                name="analytics_q_organiz_4bc0aa_idx",
            ),
        ),
    ]
