# Generated by Django 5.2.9 on 2026-01-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_querycluster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of images attached to this message: [{url, detail}]",
            ),
        ),
    ]
