# Generated by Django 5.2.9 on 2026-01-15 01:05
# Modified: Use conditional SQL for index rename + SeparateDatabaseAndState for AlterField
# 
# The database already has the correct column names (article_id, etc.) but Django's
# migration state doesn't know about them. Use SeparateDatabaseAndState to sync
# Django's understanding without modifying the actual database schema.

import django.db.models.deletion
from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if the old name exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'analytics_a_knowled_ce7603_idx'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                ALTER INDEX "analytics_a_knowled_ce7603_idx" 
                RENAME TO "analytics_a_article_ce7603_idx"
            """)


def noop(apps, schema_editor):
    """Reverse operation - no-op since we can't know the original state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_add_images_to_chatmessage"),
        ("knowledge", "0007_add_images_to_chatmessage"),
    ]

    operations = [
        # Use conditional Python instead of RenameIndex to handle missing index
        migrations.RunPython(rename_index_if_exists, noop),
        
        # Use SeparateDatabaseAndState to update Django's understanding of the schema
        # without actually modifying the database (which already has the correct structure)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="articleview",
                    name="knowledge_item",
                    field=models.ForeignKey(
                        db_column="article_id",
                        help_text="Knowledge item that was viewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_views",
                        to="knowledge.knowledgeitem",
                    ),
                ),
                migrations.AlterField(
                    model_name="contentgap",
                    name="suggested_knowledge_item",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="suggested_article_id",
                        help_text="Knowledge item created to address this gap (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_content_gaps",
                        to="knowledge.knowledgeitem",
                    ),
                ),
                migrations.AlterField(
                    model_name="search",
                    name="clicked_knowledge_item",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="clicked_article_id",
                        help_text="Knowledge item that was clicked (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_search_clicks",
                        to="knowledge.knowledgeitem",
                    ),
                ),
            ],
            database_operations=[
                # No database operations - columns already exist with correct names
            ],
        ),
    ]
