# Generated by Django 5.2.9 on 2026-01-23 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_drop_articleview_table'),
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique suggestion ID', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('missing_action', 'Missing Action'), ('low_match', 'Low Match Action'), ('not_supported', 'Not Supported')], db_index=True, help_text='Type of improvement needed', max_length=32)),
                ('stale_at', models.DateTimeField(blank=True, db_index=True, help_text='When this suggestion became stale (null = still active)', null=True)),
                ('user_goal', models.TextField(help_text='What the user was trying to accomplish')),
                ('detected_intent', models.TextField(help_text="Specific user intent that wasn't handled")),
                ('outcome_analysis', models.TextField(help_text='Explanation of why this gap exists')),
                ('confidence', models.FloatField(help_text='LLM confidence in this suggestion (0-1)')),
                ('reasoning_step_index', models.IntegerField(blank=True, help_text='Index in reasoning_trace for inline positioning', null=True)),
                ('suggestion_type', models.CharField(choices=[('action', 'Action'), ('snippet', 'Snippet')], help_text='Whether to create an action or a snippet', max_length=32)),
                ('suggested_name', models.CharField(help_text='Suggested action or snippet name', max_length=100)),
                ('suggested_description', models.TextField(help_text='Description for the action or snippet content')),
                ('code_snippet', models.TextField(help_text='Ready-to-paste code for defineActions() or snippet markdown')),
                ('cursor_prompt', models.TextField(help_text='LLM prompt wrapper for Cursor implementation guidance')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the suggestion was first created')),
                ('analyzed_at', models.DateTimeField(auto_now=True, help_text='When the suggestion was last analyzed/updated')),
                ('conversation', models.ForeignKey(help_text='Conversation this suggestion belongs to (multiple suggestions per conversation for history)', on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='analytics.chatconversation')),
                ('organization', models.ForeignKey(help_text='Organization this suggestion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='users.organization')),
                ('relevant_message', models.ForeignKey(blank=True, help_text='Message where this improvement is most relevant (for inline display)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_suggestions', to='analytics.chatmessage')),
            ],
            options={
                'verbose_name': 'Improvement Suggestion',
                'verbose_name_plural': 'Improvement Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'stale_at', '-created_at'], name='analytics_i_organiz_525c20_idx'), models.Index(fields=['organization', 'type', '-created_at'], name='analytics_i_organiz_c8e746_idx'), models.Index(fields=['conversation', '-created_at'], name='analytics_i_convers_4b83c1_idx')],
            },
        ),
    ]
