# Generated by Django 5.2.9 on 2026-01-27 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_improvementsuggestion'),
        ('products', '0015_add_default_language'),
        ('users', '0003_user_last_selected_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.product'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this message belongs to (denormalized from conversation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['product', '-started_at'], name='analytics_c_product_dd1696_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['product', 'status'], name='analytics_c_product_65c8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['product', '-timestamp'], name='analytics_c_product_903c65_idx'),
        ),
    ]
