# Generated by Django 5.2.9 on 2026-01-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_chatconversation_product_chatmessage_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="completion_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total output tokens across all LLM calls in the agentic loop",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="peak_context_occupancy",
            field=models.FloatField(
                blank=True,
                help_text="Peak context window usage percentage during the agentic loop",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="prompt_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total input tokens across all LLM calls in the agentic loop",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="prompt_tokens + completion_tokens", null=True
            ),
        ),
    ]
