# Generated by Django 5.2.9 on 2026-01-29 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_chatconversation_product_chatmessage_product_and_more'),
        ('products', '0015_add_default_language'),
        ('users', '0003_user_last_selected_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique visitor ID', primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, help_text='Persistent visitor ID from SDK (stored in localStorage)', max_length=64)),
                ('external_user_id', models.CharField(blank=True, db_index=True, help_text="Client's authenticated user ID (enables cross-device history)", max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', help_text="User's display name", max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text="User's email address", max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from client application')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the visitor was first seen')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When the visitor was last active')),
                ('organization', models.ForeignKey(help_text='Organization this visitor belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_visitors', to='users.organization')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='Visitor who initiated this conversation (enables cross-device history)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='analytics.visitor'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['visitor', '-started_at'], name='analytics_c_visitor_783003_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', 'visitor_id'], name='analytics_v_organiz_25fcac_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', 'external_user_id'], name='analytics_v_organiz_8e4cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['organization', '-last_seen_at'], name='analytics_v_organiz_eef587_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visitor_id', '-last_seen_at'], name='analytics_v_visitor_428622_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(fields=('organization', 'visitor_id'), name='analytics_visitor_org_visitor_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(condition=models.Q(('external_user_id__isnull', False)), fields=('organization', 'external_user_id'), name='analytics_visitor_org_external_user_id_uniq'),
        ),
    ]
