# Generated by Django 5.2.9 on 2026-02-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_add_token_tracking_fields'),
        ('analytics', '0013_add_visitor_model_and_conversation_fk'),
    ]

    operations = [
    ]
