# Generated by Django 5.2.9 on 2026-02-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0014_merge_20260202_1656"),
        ("products", "0017_add_action_parameter_examples"),
        ("users", "0004_update_plan_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="agent_state_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="AgentContext snapshot for resumption if interrupted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="streaming_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When streaming started (for elapsed time calculation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="streaming_status",
            field=models.CharField(
                choices=[
                    ("streaming", "Still streaming"),
                    ("completed", "Completed"),
                    ("interrupted", "Interrupted mid-stream"),
                ],
                db_index=True,
                default="streaming",
                help_text="Streaming state for session resumption",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "streaming_status"],
                name="analytics_c_convers_fc65d0_idx",
            ),
        ),
    ]
