# Generated by Django 5.2.9 on 2026-02-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0015_add_session_resumption_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="llm_messages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Full LLM messages array (excluding system prompt) for conversation continuity",
            ),
        ),
    ]
