# Generated by Django 5.2.9 on 2026-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0016_chatconversation_llm_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="thinking_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extended thinking content from Claude for display (signature stripped)",
            ),
        ),
    ]
