# Generated by Django 5.2.9 on 2026-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0017_add_thinking_content_to_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatconversation",
            name="llm_messages",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="thinking_content",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reasoning_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Opaque reasoning blocks (reasoning.encrypted, etc.) for LLM API replay",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_call_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the tool call this result responds to (for role=tool)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tool calls made by assistant: [{id, type, function: {name, arguments}}]",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, default="", help_text="Message content"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="reasoning_trace",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified timeline: [{step_type: thinking|tool_decision|tool_result, iteration, timestamp_ms, ...}]",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("tool", "Tool Result"),
                ],
                db_index=True,
                help_text="Who sent this message",
                max_length=20,
            ),
        ),
    ]
