# Generated by Django 5.2.9 on 2026-02-07 00:05
# Modified to include data migration for llm_message field

import uuid
from django.db import migrations, models


def migrate_to_llm_message(apps, schema_editor):
    """
    Migrate data from old fields (tool_calls, tool_call_id, reasoning_details, reasoning_trace)
    to new fields (llm_message, display_trace).
    """
    ChatMessage = apps.get_model('analytics', 'ChatMessage')
    
    for msg in ChatMessage.objects.all():
        # Build llm_message from old fields
        if msg.role == 'tool':
            # Tool result message
            llm_message = {
                "type": "message",
                "role": "tool",
                "tool_call_id": msg.tool_call_id or "",
                "content": msg.content or "",
            }
        else:
            # User or assistant message
            content = []
            
            # Add reasoning_details (opaque blocks for API)
            if msg.reasoning_details:
                for block in msg.reasoning_details:
                    content.append(block)
            
            # Add text content
            if msg.content:
                content.append({
                    "type": "output_text",
                    "text": msg.content,
                    "annotations": [],
                })
            
            # Add tool_calls
            if msg.tool_calls:
                for tc in msg.tool_calls:
                    content.append({
                        "type": "tool_use",
                        "id": tc.get("id", ""),
                        "name": tc.get("function", {}).get("name", ""),
                        "input": tc.get("function", {}).get("arguments", {}),
                    })
            
            llm_message = {
                "type": "message",
                "role": msg.role,
                "id": f"msg_{uuid.uuid4().hex[:12]}",
                "status": "completed",
                "content": content,
            }
        
        # Copy reasoning_trace to display_trace
        display_trace = msg.reasoning_trace or []
        
        # Update the message
        msg.llm_message = llm_message
        msg.display_trace = display_trace
        msg.save(update_fields=['llm_message', 'display_trace'])


def reverse_migrate(apps, schema_editor):
    """
    Reverse migration - clear new fields (data loss, but old fields still exist).
    """
    ChatMessage = apps.get_model('analytics', 'ChatMessage')
    ChatMessage.objects.update(llm_message={}, display_trace=[])


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0018_add_llm_native_fields_to_chatmessage"),
    ]

    operations = [
        # Step 1: Add new fields
        migrations.AddField(
            model_name="chatmessage",
            name="display_trace",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Human-readable timeline for UI: [{step_type: thinking|tool_decision|tool_result, content, timestamp_ms, ...}]",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="llm_message",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete LLM message for conversation replay (OpenRouter format: {type, role, id, status, content: [...]})",
            ),
        ),
        
        # Step 2: Migrate data from old fields to new fields
        migrations.RunPython(migrate_to_llm_message, reverse_migrate),
        
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name="chatmessage",
            name="reasoning_details",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="reasoning_trace",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="tool_call_id",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="tool_calls",
        ),
        
        # Step 4: Update content field help_text
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Message content (final text for display)",
            ),
        ),
    ]
