# Generated by Django 5.2.9 on 2026-02-09 17:49
# Modified: Use SeparateDatabaseAndState for FK removal on models being deleted.
# The DB may be missing columns (e.g. suggested_article_id was already removed),
# so we update Django state only and let DeleteModel drop the tables.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0019_simplify_llm_fields"),
    ]

    operations = [
        # State-only FK removal for models about to be deleted.
        # The subsequent DeleteModel (DROP TABLE) handles actual DB cleanup.
        # This avoids failures when columns are already missing from the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="contentgap",
                    name="organization",
                ),
                migrations.RemoveField(
                    model_name="contentgap",
                    name="suggested_knowledge_item",
                ),
                migrations.RemoveField(
                    model_name="improvementsuggestion",
                    name="conversation",
                ),
                migrations.RemoveField(
                    model_name="improvementsuggestion",
                    name="organization",
                ),
                migrations.RemoveField(
                    model_name="improvementsuggestion",
                    name="relevant_message",
                ),
                migrations.RemoveField(
                    model_name="querycluster",
                    name="organization",
                ),
                migrations.RemoveField(
                    model_name="chatmessage",
                    name="primary_cluster",
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveIndex(
            model_name="chatmessage",
            name="analytics_c_primary_2107fc_idx",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="cluster_confidence",
        ),
        migrations.DeleteModel(
            name="ContentGap",
        ),
        migrations.DeleteModel(
            name="ImprovementSuggestion",
        ),
        migrations.DeleteModel(
            name="QueryCluster",
        ),
    ]
