# Generated by Django 5.2.9 on 2026-02-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0019_simplify_llm_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentgap",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="contentgap",
            name="suggested_knowledge_item",
        ),
        migrations.RemoveField(
            model_name="improvementsuggestion",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="improvementsuggestion",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="improvementsuggestion",
            name="relevant_message",
        ),
        migrations.RemoveField(
            model_name="querycluster",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="primary_cluster",
        ),
        migrations.RemoveIndex(
            model_name="chatmessage",
            name="analytics_c_primary_2107fc_idx",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="cluster_confidence",
        ),
        migrations.DeleteModel(
            name="ContentGap",
        ),
        migrations.DeleteModel(
            name="ImprovementSuggestion",
        ),
        migrations.DeleteModel(
            name="QueryCluster",
        ),
    ]
