# Generated by Django 5.2.9 on 2026-02-09 21:31

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0020_remove_unused_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                help_text="Unique conversation ID",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                help_text="Unique message ID",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                help_text="Unique visitor ID",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="widgetsession",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
