# Generated by Django 5.2.9 on 2026-02-10 19:04
#
# Fixes a production issue where migration 0002_initial was faked,
# so the clicked_article_id column on analytics_search was never created.
# Django's migration state thinks it exists, but the DB doesn't have it.

from django.db import migrations


def add_missing_columns(apps, schema_editor):
    """Conditionally add FK columns that were supposed to be created by 0002_initial."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check and add clicked_article_id on analytics_search
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'analytics_search'
                AND column_name = 'clicked_article_id'
            )
        """)
        if not cursor.fetchone()[0]:
            cursor.execute("""
                ALTER TABLE analytics_search
                ADD COLUMN clicked_article_id uuid NULL
                REFERENCES knowledge_item(id)
                ON DELETE SET NULL
            """)
            cursor.execute("""
                CREATE INDEX analytics_search_clicked_article_id_idx
                ON analytics_search(clicked_article_id)
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0021_alter_chatconversation_id_alter_chatmessage_id_and_more"),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
    ]
