# Generated by Django 5.2.9 on 2026-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0022_fix_missing_clicked_article_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="streaming_status",
            field=models.CharField(
                choices=[
                    ("streaming", "Still streaming"),
                    ("completed", "Completed"),
                    ("interrupted", "Interrupted mid-stream"),
                    ("disconnected", "Client disconnected"),
                ],
                db_index=True,
                default="streaming",
                help_text="Streaming state for session resumption",
                max_length=20,
            ),
        ),
    ]
