# Generated by Django 5.2.9 on 2026-02-10 20:22

from django.db import migrations


def flip_interrupted_to_disconnected(apps, schema_editor):
    """Flip existing 'interrupted' rows to 'disconnected' so they become resumable."""
    ChatMessage = apps.get_model('analytics', 'ChatMessage')
    ChatMessage.objects.filter(streaming_status='interrupted').update(streaming_status='disconnected')


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0023_add_disconnected_streaming_status"),
    ]

    operations = [
        migrations.RunPython(flip_interrupted_to_disconnected, migrations.RunPython.noop),
    ]
