# Generated by Django 5.2.9 on 2026-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0024_migrate_interrupted_to_disconnected"),
        ("products", "0026_backfill_channel_compatibility"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("slack", "Slack"),
                    ("discord", "Discord"),
                    ("email", "Email"),
                    ("api", "Api"),
                    ("whatsapp", "Whatsapp"),
                    ("teams", "Teams"),
                    ("telegram", "Telegram"),
                    ("sms", "Sms"),
                ],
                db_index=True,
                default="web",
                help_text="Channel this conversation originated from",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["organization", "channel", "-started_at"],
                name="chatconv_org_chan_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["product", "channel", "-started_at"],
                name="chatconv_prod_chan_start_idx",
            ),
        ),
    ]
