# Generated by Django 5.2.9 on 2026-03-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0025_add_channel_to_chatconversation"),
        ("products", "0032_migrate_web_agents"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent that handled this conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="products.agent",
            ),
        ),
    ]
