# Generated by Django 5.2.9 on 2026-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0026_add_agent_to_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("slack", "Slack"),
                    ("discord", "Discord"),
                    ("email", "Email"),
                    ("api", "Api"),
                    ("mcp", "Mcp"),
                    ("whatsapp", "Whatsapp"),
                    ("teams", "Teams"),
                    ("telegram", "Telegram"),
                    ("sms", "Sms"),
                ],
                db_index=True,
                default="web",
                help_text="Channel this conversation originated from",
                max_length=20,
            ),
        ),
    ]
