# Generated by Django 5.2.9 on 2026-03-18 18:12

import django.db.models.deletion
import encrypted_fields.fields
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0025_add_channel_to_chatconversation"),
        ("products", "0030_product_identity_auto_link_by_email_and_more"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_id",
                    models.CharField(
                        db_index=True,
                        help_text="Slack workspace (team) ID, e.g. T04ABCDEF",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        help_text="Human-readable workspace name", max_length=255
                    ),
                ),
                (
                    "bot_token",
                    encrypted_fields.fields.EncryptedTextField(
                        help_text="xoxb-... bot token. Encrypted at rest via Fernet."
                    ),
                ),
                (
                    "bot_user_id",
                    models.CharField(
                        help_text="Bot user ID in the workspace, e.g. U04BOTID",
                        max_length=50,
                    ),
                ),
                (
                    "installing_user_id",
                    models.CharField(
                        help_text="Slack user ID of the person who installed the app",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False if uninstalled or deactivated from dashboard",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OAuth scopes granted at install time",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Channel configuration: allowed_channels, dm_enabled, identity_link_url, etc.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this Slack workspace is connected to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_installations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Installation",
                "verbose_name_plural": "Slack Installations",
            },
        ),
        migrations.CreateModel(
            name="SlackConversationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_id",
                    models.CharField(
                        db_index=True,
                        help_text="Slack channel ID (C..., D..., or G...)",
                        max_length=50,
                    ),
                ),
                (
                    "thread_ts",
                    models.CharField(
                        db_index=True,
                        help_text="Parent message timestamp that defines the thread",
                        max_length=50,
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_mapping",
                        to="analytics.chatconversation",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_mappings",
                        to="slack_integration.slackinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Conversation Mapping",
                "verbose_name_plural": "Slack Conversation Mappings",
            },
        ),
        migrations.AddIndex(
            model_name="slackinstallation",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="slack_integ_organiz_4895dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slackinstallation",
            index=models.Index(
                fields=["organization", "-updated_at"],
                name="slack_integ_organiz_e3bab4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slackinstallation",
            index=models.Index(
                fields=["product", "is_active"], name="slack_integ_product_d6cec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slackconversationmapping",
            index=models.Index(
                fields=["installation", "channel_id", "thread_ts"],
                name="idx_slack_conv_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="slackconversationmapping",
            constraint=models.UniqueConstraint(
                fields=("installation", "channel_id", "thread_ts"),
                name="uq_slack_conv_mapping",
            ),
        ),
    ]
