# Generated by Django 5.2.9 on 2026-03-19 04:23

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0034_agent_knowledge_scope_agent_knowledge_sources"),
        ("slack_integration", "0001_initial"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackinstallation",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific agent to route messages to. Null = use product+channel resolver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slack_installations",
                to="products.agent",
            ),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="app_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Slack app ID (api_app_id). Empty for legacy OAuth installs.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="is_byob",
            field=models.BooleanField(
                default=False,
                help_text="True if customer provided their own Slack app credentials.",
            ),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="signing_secret",
            field=encrypted_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Per-installation signing secret for BYOB apps. Empty = use global.",
            ),
        ),
        migrations.AlterField(
            model_name="slackinstallation",
            name="installing_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slack user ID of the person who installed the app",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="slackinstallation",
            name="team_id",
            field=models.CharField(
                db_index=True,
                help_text="Slack workspace (team) ID, e.g. T04ABCDEF",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="slackinstallation",
            constraint=models.UniqueConstraint(
                fields=("team_id", "app_id"), name="uq_slack_team_app"
            ),
        ),
    ]
