# Generated by Django 5.2.9 on 2026-03-19 05:20

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slack_integration", "0002_byob_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackinstallation",
            name="signing_secret",
            field=encrypted_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Per-installation signing secret for BYOB apps. Empty = use global.",
                null=True,
            ),
        ),
    ]
