# Generated by Django 5.2.9 on 2026-03-17 22:36

import common.fields
import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0027_add_sync_secret_rotation_fields"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPToolSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g. 'Acme internal tools')",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="MCP server Streamable HTTP endpoint URL",
                        max_length=500,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer Token"),
                            ("header", "Custom Header"),
                            ("oauth", "OAuth 2.1"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "auth_credentials",
                    common.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Auth credentials (encrypted). JSON: {'token': '...'} or {'header_name': '...', 'header_value': '...'}",
                    ),
                ),
                (
                    "discovered_tools",
                    models.JSONField(
                        default=list,
                        help_text="Tool schemas returned by the last tools/list call",
                    ),
                ),
                (
                    "last_discovery_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When tools/list was last called",
                        null=True,
                    ),
                ),
                (
                    "discovery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "discovery_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message from the last failed discovery",
                    ),
                ),
                ("last_ping_at", models.DateTimeField(blank=True, null=True)),
                ("last_ping_success", models.BooleanField(default=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this MCP source belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_sources",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Tool Source",
                "verbose_name_plural": "MCP Tool Sources",
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="mcpsrc_product_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ToolEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint_url",
                    models.URLField(
                        help_text="URL where Pillar POSTs tool calls", max_length=500
                    ),
                ),
                (
                    "registered_tools",
                    models.JSONField(
                        default=list,
                        help_text="List of tool schemas registered by the SDK",
                    ),
                ),
                (
                    "sdk_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SDK identifier sent during registration (e.g. 'pillar-python/0.1.0')",
                        max_length=100,
                    ),
                ),
                (
                    "last_call_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a tool call was dispatched to this endpoint",
                        null=True,
                    ),
                ),
                (
                    "last_ping_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a health-check ping was sent",
                        null=True,
                    ),
                ),
                (
                    "last_ping_success",
                    models.BooleanField(
                        default=True, help_text="Whether the most recent ping succeeded"
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of consecutive ping failures"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this endpoint accepts tool calls",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this endpoint serves",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_endpoints",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Endpoint",
                "verbose_name_plural": "Tool Endpoints",
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="toolep_product_active_idx",
                    )
                ],
            },
        ),
    ]
