# Generated by Django 5.2.9 on 2026-03-17 22:48

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcptoolsource",
            name="auth_credentials",
            field=common.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Auth credentials (encrypted). JSON: {'token': '...'} or {'header_name': '...', 'header_value': '...'}",
                null=True,
            ),
        ),
    ]
