# Generated by Django 5.2.9 on 2026-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0042_composable_mcp_sources"),
        ("tools", "0002_alter_mcptoolsource_auth_credentials"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptoolsource",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Short identifier used to namespace tool names (e.g. 'datadog')",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcptoolsource",
            constraint=models.UniqueConstraint(
                fields=("product", "slug"), name="mcpsrc_product_slug_uniq"
            ),
        ),
    ]
