# Generated by Django 5.2.9 on 2026-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_composable_mcp_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_authorization_endpoint",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External server's OAuth authorization endpoint",
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client ID obtained via Dynamic Client Registration",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_registration_endpoint",
            field=models.URLField(
                blank=True, default="", help_text="External server's DCR endpoint"
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_scopes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Space-separated OAuth scopes requested",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_status",
            field=models.CharField(
                choices=[
                    ("none", "N/A"),
                    ("discovering", "Discovering"),
                    ("authorization_required", "Authorization Required"),
                    ("authorized", "Authorized"),
                    ("expired", "Token Expired"),
                    ("error", "Error"),
                ],
                default="none",
                help_text="Current state of the OAuth authorization flow",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_token_endpoint",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External server's OAuth token endpoint",
            ),
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_token_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the current access token expires", null=True
            ),
        ),
    ]
