# Generated by Django 5.2.9 on 2026-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_mcptoolsource_oauth_authorization_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcptoolsource",
            name="last_ping_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="toolendpoint",
            name="last_ping_success",
            field=models.BooleanField(
                default=False, help_text="Whether the most recent ping succeeded"
            ),
        ),
    ]
