# Generated by Django 5.2.9 on 2026-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0005_alter_mcptoolsource_last_ping_success_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptoolsource",
            name="discovered_resources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Resource descriptors from the last resources/list call, with embeddings",
            ),
        ),
    ]
