# Generated by Django 5.2.9 on 2026-03-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_discovered_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptoolsource",
            name="discovered_prompts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Prompt definitions from the last prompts/list call",
            ),
        ),
    ]
