# Generated by Django 5.2.9 on 2026-03-23 22:39

import common.fields
import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0042_composable_mcp_sources"),
        ("tools", "0007_discovered_prompts"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAPIToolSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g. 'Acme API')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Short identifier to namespace tool names (e.g. 'acme')",
                    ),
                ),
                (
                    "spec_url",
                    models.URLField(
                        help_text="URL to the OpenAPI spec (JSON or YAML)",
                        max_length=500,
                    ),
                ),
                (
                    "spec_format",
                    models.CharField(
                        blank=True,
                        default="json",
                        help_text="Format of the spec: 'json' or 'yaml'",
                        max_length=10,
                    ),
                ),
                (
                    "spec_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API version from spec info.version",
                        max_length=50,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Base URL for API calls (overrides spec servers[0].url)",
                        max_length=500,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("oauth2_client_credentials", "OAuth2 Client Credentials"),
                            ("oauth2_authorization_code", "OAuth2 Authorization Code"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "auth_credentials",
                    common.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Encrypted org-level credentials. JSON: {'token': '...'} or {'header_name': '...', 'header_value': '...'}",
                        null=True,
                    ),
                ),
                (
                    "oauth_client_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OAuth client ID for the customer's authorization server",
                        max_length=255,
                    ),
                ),
                (
                    "oauth_client_secret",
                    common.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="OAuth client secret (encrypted at rest)",
                        null=True,
                    ),
                ),
                (
                    "oauth_authorization_endpoint",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="OAuth authorization endpoint URL",
                    ),
                ),
                (
                    "oauth_token_endpoint",
                    models.URLField(
                        blank=True, default="", help_text="OAuth token endpoint URL"
                    ),
                ),
                (
                    "oauth_scopes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Space-separated OAuth scopes to request",
                        max_length=500,
                    ),
                ),
                (
                    "discovered_operations",
                    models.JSONField(
                        default=list,
                        help_text="Parsed operations from the OpenAPI spec, with input schemas and embeddings",
                    ),
                ),
                (
                    "last_discovery_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the spec was last fetched and parsed",
                        null=True,
                    ),
                ),
                (
                    "discovery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "discovery_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message from the last failed spec parse",
                    ),
                ),
                ("last_ping_at", models.DateTimeField(blank=True, null=True)),
                ("last_ping_success", models.BooleanField(default=False)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this OpenAPI source belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openapi_sources",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAPI Tool Source",
                "verbose_name_plural": "OpenAPI Tool Sources",
            },
        ),
        migrations.CreateModel(
            name="OAuthLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Cryptographically random token used as OAuth state",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("channel", models.CharField(max_length=50)),
                ("channel_user_id", models.CharField(max_length=255)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token expires after 10 minutes"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True after successful OAuth callback",
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "openapi_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_tokens",
                        to="tools.openapitoolsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Link Token",
                "verbose_name_plural": "OAuth Link Tokens",
            },
        ),
        migrations.CreateModel(
            name="UserToolCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        help_text="Channel where the user authenticated (web, slack, discord, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "channel_user_id",
                    models.CharField(
                        help_text="User identifier on the channel (Slack user ID, Discord snowflake, visitor_id)",
                        max_length=255,
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Customer-side user ID (from IdentityMapping), nullable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    common.fields.EncryptedTextField(
                        help_text="OAuth access token (encrypted at rest)"
                    ),
                ),
                (
                    "refresh_token",
                    common.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="OAuth refresh token (encrypted at rest)",
                        null=True,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer",
                        help_text="Token type (usually 'Bearer')",
                        max_length=50,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                (
                    "scopes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Space-separated scopes granted by this token",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Set to False when token is revoked or refresh fails irrecoverably",
                    ),
                ),
                (
                    "openapi_source",
                    models.ForeignKey(
                        help_text="Which OpenAPI source these credentials are for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_credentials",
                        to="tools.openapitoolsource",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tool_credentials",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tool Credential",
                "verbose_name_plural": "User Tool Credentials",
            },
        ),
        migrations.AddIndex(
            model_name="openapitoolsource",
            index=models.Index(
                fields=["product", "is_active"], name="openapisrc_product_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="openapitoolsource",
            constraint=models.UniqueConstraint(
                fields=("product", "slug"), name="openapisrc_product_slug_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="usertoolcredential",
            index=models.Index(
                fields=["openapi_source", "is_active"],
                name="usertoolcred_source_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertoolcredential",
            constraint=models.UniqueConstraint(
                fields=("openapi_source", "channel", "channel_user_id"),
                name="usertoolcred_source_chan_user_uniq",
            ),
        ),
    ]
