# Generated by Django 5.2.9 on 2026-03-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_openapi_tool_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapitoolsource",
            name="spec_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw OpenAPI spec content (JSON or YAML). Mutually exclusive with spec_url.",
            ),
        ),
        migrations.AlterField(
            model_name="openapitoolsource",
            name="spec_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to the OpenAPI spec (JSON or YAML). Mutually exclusive with spec_content.",
                max_length=500,
            ),
        ),
    ]
