# Generated by Django 5.2.9 on 2026-03-24 01:19

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0009_openapi_spec_content"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapitoolsource",
            name="current_version_number",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-incrementing version counter, bumped on each spec update",
            ),
        ),
        migrations.CreateModel(
            name="OpenAPIToolSourceVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Monotonically increasing counter (1, 2, 3...)"
                    ),
                ),
                (
                    "spec_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API version from spec info.version (e.g. '1.0.0')",
                        max_length=50,
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Revision within the same spec_version (1 for first, 2+ for duplicates)",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional user-provided suffix (e.g. 'scopes-fix')",
                        max_length=100,
                    ),
                ),
                ("spec_content", models.TextField(blank=True, default="")),
                ("spec_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "spec_format",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("discovered_operations", models.JSONField(blank=True, default=list)),
                ("operation_count", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="tools.openapitoolsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAPI Tool Source Version",
                "verbose_name_plural": "OpenAPI Tool Source Versions",
                "ordering": ["-version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "version_number"),
                        name="openapiver_source_vernum_uniq",
                    )
                ],
            },
        ),
    ]
