# Generated by Django 5.2.9 on 2026-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0010_openapi_source_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthlinktoken",
            name="code_verifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PKCE code_verifier stored during authorize, sent during token exchange",
                max_length=128,
            ),
        ),
    ]
