# Generated by Django 5.2.9 on 2026-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0011_pkce_code_verifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthlinktoken",
            name="oauth_environment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which OAuth environment this link is for",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="openapitoolsource",
            name="oauth_environments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of OAuth environments, e.g. [{"name": "Sandbox", "extra_scope": "env:sandbox"}]',
            ),
        ),
        migrations.AddField(
            model_name="usertoolcredential",
            name="oauth_environment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which OAuth environment this credential is for (e.g. 'sandbox', 'live')",
                max_length=100,
            ),
        ),
    ]
