# Generated by Django 5.2.9 on 2026-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0012_oauth_environments"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapitoolsource",
            name="oauth_token_exchange_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional. POST to this URL with Bearer {oauth_token} after OAuth to provision API keys. Response JSON field is specified per-environment via credential_key.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="openapitoolsource",
            name="oauth_environments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of OAuth environments, e.g. [{"name": "Sandbox", "extra_scope": "env:sandbox", "credential_key": "sandbox_key"}]',
            ),
        ),
    ]
