# Generated by Django 5.2.9 on 2026-03-24 18:05

from django.db import migrations, models


CONFIRMATION_DEFAULT = ["DELETE", "PATCH", "PUT", "POST"]


def backfill_confirmation_defaults(apps, schema_editor):
    """Set smart defaults on existing OpenAPI sources."""
    OpenAPIToolSource = apps.get_model("tools", "OpenAPIToolSource")
    OpenAPIToolSource.objects.filter(
        confirmation_default_methods=[],
    ).update(confirmation_default_methods=CONFIRMATION_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0013_oauth_token_exchange_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="openapitoolsource",
            name="confirmation_default_methods",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "HTTP methods requiring confirmation by default. "
                    "Defaults to all mutating methods (DELETE, PATCH, PUT, POST)."
                ),
            ),
        ),
        migrations.RunPython(
            backfill_confirmation_defaults,
            migrations.RunPython.noop,
        ),
    ]
