# Generated by Django 5.2.9 on 2026-03-24 18:08

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0044_agentopenapisource_alter_agent_openapi_sources_and_more"),
        ("tools", "0014_openapitoolsource_confirmation_default_methods"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique skill name (e.g. 'autumn-setup')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="When/why to use this skill"),
                ),
                (
                    "content",
                    models.TextField(help_text="Full skill content (markdown)"),
                ),
                (
                    "description_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("cli_sync", "CLI Sync"),
                            ("backend_sdk", "Backend SDK"),
                            ("manual", "Manual"),
                        ],
                        default="backend_sdk",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Server SDK endpoint that registered this skill (null for CLI sync)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="tools.toolendpoint",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this skill belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_skills",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered Skill",
                "verbose_name_plural": "Registered Skills",
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"], name="regskill_prod_active_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["description_embedding"],
                        m=16,
                        name="regskill_desc_emb_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "name"), name="regskill_product_name_uniq"
                    )
                ],
            },
        ),
    ]
