# Generated by Django 5.2.9 on 2026-03-24 18:18

from django.db import migrations, models


def _default_confirmation_methods():
    return ["DELETE", "PATCH", "PUT", "POST"]


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0015_add_registered_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openapitoolsource",
            name="confirmation_default_methods",
            field=models.JSONField(
                blank=True,
                default=_default_confirmation_methods,
                help_text="HTTP methods requiring confirmation by default. Defaults to all mutating methods (DELETE, PATCH, PUT, POST).",
            ),
        ),
    ]
