# Generated by Django 5.2.9 on 2026-03-24 18:28

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


MUTATING_METHODS = {"DELETE", "PATCH", "PUT", "POST"}


def backfill_operation_configs(apps, schema_editor):
    """Convert existing confirmation_default_methods + discovered_operations
    into OpenAPIOperationConfig rows."""
    OpenAPIToolSource = apps.get_model("tools", "OpenAPIToolSource")
    OpenAPIOperationConfig = apps.get_model("tools", "OpenAPIOperationConfig")

    for source in OpenAPIToolSource.objects.all():
        confirm_methods = set(
            m.upper() for m in (source.confirmation_default_methods or [])
        )
        if not confirm_methods:
            confirm_methods = MUTATING_METHODS

        configs = []
        for op in source.discovered_operations or []:
            op_id = op.get("operation_id")
            if not op_id:
                continue
            method = op.get("method", "").upper()
            configs.append(OpenAPIOperationConfig(
                openapi_source=source,
                operation_id=op_id,
                is_enabled=True,
                requires_confirmation=method in confirm_methods,
            ))

        if configs:
            OpenAPIOperationConfig.objects.bulk_create(configs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0016_alter_openapitoolsource_confirmation_default_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAPIOperationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_id", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(default=True)),
                ("requires_confirmation", models.BooleanField(default=False)),
                (
                    "openapi_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_configs",
                        to="tools.openapitoolsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAPI Operation Config",
                "verbose_name_plural": "OpenAPI Operation Configs",
                "indexes": [
                    models.Index(
                        fields=["openapi_source"], name="openapi_opconfig_source_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("openapi_source", "operation_id"),
                        name="openapi_op_config_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_operation_configs,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="openapitoolsource",
            name="confirmation_default_methods",
        ),
    ]
