# Generated by Django 5.2.9 on 2026-03-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0046_mcp_through_tables_and_rename"),
        ("tools", "0018_rename_operation_id_and_mcp_tool_config"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usertoolcredential",
            name="usertoolcred_source_chan_user_uniq",
        ),
        migrations.RenameIndex(
            model_name="usertoolcredential",
            new_name="utcred_openapi_active_idx",
            old_name="usertoolcred_source_active_idx",
        ),
        migrations.AddField(
            model_name="mcptoolsource",
            name="oauth_mode",
            field=models.CharField(
                choices=[
                    ("org", "Organization (admin authenticates once)"),
                    ("client", "Per-user (each end-user authenticates)"),
                ],
                default="org",
                help_text="Whether OAuth tokens are shared org-wide or per end-user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="oauthlinktoken",
            name="mcp_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_tokens",
                to="tools.mcptoolsource",
            ),
        ),
        migrations.AddField(
            model_name="usertoolcredential",
            name="mcp_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Which MCP source these credentials are for (client-auth mode)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_credentials",
                to="tools.mcptoolsource",
            ),
        ),
        migrations.AlterField(
            model_name="oauthlinktoken",
            name="openapi_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_tokens",
                to="tools.openapitoolsource",
            ),
        ),
        migrations.AlterField(
            model_name="usertoolcredential",
            name="openapi_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Which OpenAPI source these credentials are for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_credentials",
                to="tools.openapitoolsource",
            ),
        ),
        migrations.AddIndex(
            model_name="usertoolcredential",
            index=models.Index(
                fields=["mcp_source", "is_active"], name="utcred_mcp_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthlinktoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("mcp_source__isnull", True), ("openapi_source__isnull", False)
                    ),
                    models.Q(
                        ("mcp_source__isnull", False), ("openapi_source__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="oauthlinktoken_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertoolcredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("openapi_source__isnull", False)),
                fields=("openapi_source", "channel", "channel_user_id"),
                name="usertoolcred_openapi_chan_user_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertoolcredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mcp_source__isnull", False)),
                fields=("mcp_source", "channel", "channel_user_id"),
                name="usertoolcred_mcp_chan_user_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertoolcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("mcp_source__isnull", True), ("openapi_source__isnull", False)
                    ),
                    models.Q(
                        ("mcp_source__isnull", False), ("openapi_source__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="usertoolcred_exactly_one_source",
            ),
        ),
    ]
