"""
Management command to generate a Python CLI client from registered tools.

Usage:
    python manage.py generate_cli --product-id <uuid> --output ./cli --name acme

Generates a self-contained Python Click CLI with:
- One command per registered tool
- An `ask` command that calls the headless SSE API
- Proper argument parsing from tool JSON schemas
"""
import json
import os
import textwrap

from django.core.management.base import BaseCommand, CommandError

SETUP_PY_TEMPLATE = '''\
from setuptools import setup, find_packages

setup(
    name="{name}-cli",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "click>=8.0",
        "httpx>=0.26",
    ],
    entry_points={{
        "console_scripts": [
            "{name}={name}_cli.main:cli",
        ],
    }},
)
'''

MAIN_PY_HEADER = '''\
"""
Auto-generated CLI for {name}.

Generated by: pillar generate_cli
"""
import json
import sys

import click
import httpx

API_BASE_URL = "{api_url}"


def _get_api_key():
    """Read API key from env or config."""
    import os
    key = os.environ.get("{env_var}")
    if not key:
        click.echo(
            f"Error: Set {env_var} environment variable with your Pillar API key.",
            err=True,
        )
        sys.exit(1)
    return key


@click.group()
def cli():
    """{description}"""
    pass

'''

ASK_COMMAND = '''\
@cli.command()
@click.argument("question", nargs=-1, required=True)
@click.option("--conversation-id", "-c", default=None, help="Continue an existing conversation")
def ask(question, conversation_id):
    """Ask the AI agent a question (streaming)."""
    question_text = " ".join(question)
    api_key = _get_api_key()

    payload = {{"message": question_text}}
    if conversation_id:
        payload["conversation_id"] = conversation_id

    with httpx.Client(timeout=120) as client:
        with client.stream(
            "POST",
            f"{{API_BASE_URL}}/api/chat/stream/",
            json=payload,
            headers={{"Authorization": f"Bearer {{api_key}}"}},
        ) as response:
            if response.status_code != 200:
                click.echo(f"Error: HTTP {{response.status_code}}", err=True)
                sys.exit(1)

            conv_id = None
            for line in response.iter_lines():
                if line.startswith("event: "):
                    event_type = line[7:]
                elif line.startswith("data: "):
                    data = json.loads(line[6:])
                    if event_type == "token":
                        click.echo(data.get("token", ""), nl=False)
                    elif event_type == "conversation":
                        conv_id = data.get("conversation_id")
                    elif event_type == "sources":
                        sources = data.get("sources", [])
                        if sources:
                            click.echo("\\n\\nSources:")
                            for s in sources:
                                title = s.get("title", "")
                                url = s.get("url", "")
                                click.echo(f"  - {{title}} {{url}}")
                    elif event_type == "complete":
                        pass
                    elif event_type == "error":
                        click.echo(f"\\nError: {{data.get('message', '')}}", err=True)

            click.echo()
            if conv_id:
                click.echo(f"[conversation: {{conv_id}}]", err=True)

'''

TOOL_COMMAND_TEMPLATE = '''\
@cli.command(name="{command_name}")
{click_params}def {func_name}({func_args}):
    """{description}"""
    api_key = _get_api_key()

    payload = {{
        "message": "Please execute the {tool_name} tool with the following parameters: " +
                   json.dumps({{{param_dict}}}),
    }}

    with httpx.Client(timeout=60) as client:
        resp = client.post(
            f"{{API_BASE_URL}}/api/chat/",
            json=payload,
            headers={{"Authorization": f"Bearer {{api_key}}"}},
        )

        if resp.status_code != 200:
            click.echo(f"Error: HTTP {{resp.status_code}}: {{resp.text}}", err=True)
            sys.exit(1)

        result = resp.json()
        click.echo(result.get("response", result.get("message", "")))

        sources = result.get("sources", [])
        if sources:
            click.echo("\\nSources:")
            for s in sources:
                click.echo(f"  - {{s.get('title', '')}} {{s.get('url', '')}}")

'''


class Command(BaseCommand):
    help = "Generate a Python CLI client from registered tools"

    def add_arguments(self, parser):
        parser.add_argument(
            '--product-id', required=True,
            help='Product UUID to generate CLI for',
        )
        parser.add_argument(
            '--output', '-o', default='./generated-cli',
            help='Output directory for the generated CLI',
        )
        parser.add_argument(
            '--name', '-n', default='pillar',
            help='CLI name (used for the command and package name)',
        )
        parser.add_argument(
            '--api-url', default='https://help-api.trypillar.com',
            help='Pillar API base URL',
        )

    def handle(self, *args, **options):
        from apps.products.models import Action, Product

        product_id = options['product_id']
        output_dir = options['output']
        name = options['name']
        api_url = options['api_url'].rstrip('/')

        try:
            product = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            raise CommandError(f"Product {product_id} not found")

        actions = Action.objects.filter(
            product=product, is_active=True,
        ).order_by('name')

        if not actions.exists():
            self.stderr.write(self.style.WARNING(
                f"No active tools registered for product {product.name}. "
                "The CLI will only have the 'ask' command."
            ))

        package_dir = os.path.join(output_dir, f"{name}_cli")
        os.makedirs(package_dir, exist_ok=True)

        # Write setup.py
        setup_path = os.path.join(output_dir, 'setup.py')
        with open(setup_path, 'w') as f:
            f.write(SETUP_PY_TEMPLATE.format(name=name))

        # Write requirements.txt
        req_path = os.path.join(output_dir, 'requirements.txt')
        with open(req_path, 'w') as f:
            f.write("click>=8.0\nhttpx>=0.26\n")

        # Write __init__.py
        init_path = os.path.join(package_dir, '__init__.py')
        with open(init_path, 'w') as f:
            f.write('')

        # Build main.py
        env_var = f"{name.upper()}_API_KEY"
        description = f"{product.name} CLI — powered by Pillar"

        main_content = MAIN_PY_HEADER.format(
            name=name,
            api_url=api_url,
            env_var=env_var,
            description=description,
        )

        main_content += ASK_COMMAND

        for action in actions:
            cmd = self._generate_tool_command(action)
            if cmd:
                main_content += cmd

        main_content += '\nif __name__ == "__main__":\n    cli()\n'

        main_path = os.path.join(package_dir, 'main.py')
        with open(main_path, 'w') as f:
            f.write(main_content)

        readme_path = os.path.join(output_dir, 'README.md')
        with open(readme_path, 'w') as f:
            f.write(f"# {name} CLI\n\n")
            f.write(f"Auto-generated CLI for {product.name}.\n\n")
            f.write("## Setup\n\n")
            f.write("```bash\n")
            f.write("pip install -e .\n")
            f.write(f"export {env_var}=sk_live_...\n")
            f.write("```\n\n")
            f.write("## Usage\n\n")
            f.write("```bash\n")
            f.write(f"# Ask a question\n")
            f.write(f"{name} ask How do I reset my password?\n\n")
            for action in actions:
                f.write(f"# {action.description[:60] if action.description else action.name}\n")
                f.write(f"{name} {action.name.replace('_', '-')}\n")
            f.write("```\n")

        tool_count = actions.count()
        self.stdout.write(self.style.SUCCESS(
            f"Generated CLI at {output_dir}/ with {tool_count} tool command(s) + ask"
        ))

    def _generate_tool_command(self, action) -> str | None:
        """Generate a Click command for a registered tool action."""
        schema = action.input_schema or {}
        properties = schema.get('properties', {})
        required_fields = set(schema.get('required', []))

        command_name = action.name.replace('_', '-')
        func_name = action.name.replace('-', '_').replace('.', '_')
        description = action.description or f"Execute {action.name}"

        click_params = []
        func_args = []
        param_items = []

        for prop_name, prop_schema in properties.items():
            prop_type = prop_schema.get('type', 'string')
            prop_desc = prop_schema.get('description', '')
            is_required = prop_name in required_fields
            arg_name = prop_name.replace('-', '_')

            click_type = 'str'
            if prop_type == 'integer':
                click_type = 'int'
            elif prop_type == 'number':
                click_type = 'float'
            elif prop_type == 'boolean':
                click_type = 'bool'

            option_name = f"--{prop_name.replace('_', '-')}"

            if is_required:
                click_params.append(
                    f'@click.option("{option_name}", required=True, type={click_type}, help="{prop_desc}")\n'
                )
            else:
                default = prop_schema.get('default', None)
                default_repr = repr(default)
                click_params.append(
                    f'@click.option("{option_name}", default={default_repr}, type={click_type}, help="{prop_desc}")\n'
                )

            func_args.append(arg_name)
            param_items.append(f'"{prop_name}": {arg_name}')

        click_params_str = ''.join(click_params)
        func_args_str = ', '.join(func_args) if func_args else ''
        param_dict_str = ', '.join(param_items)

        return TOOL_COMMAND_TEMPLATE.format(
            command_name=command_name,
            click_params=click_params_str,
            func_name=func_name,
            func_args=func_args_str,
            description=description[:200],
            tool_name=action.name,
            param_dict=param_dict_str,
        )
