# Generated by Django 5.2.9 on 2026-03-18 23:18

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0026_add_agent_to_conversation"),
        ("products", "0032_migrate_web_agents"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChannelConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inbound_address",
                    models.EmailField(
                        help_text="Inbound email address, e.g. support-acme@inbound.trypillar.com",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Display name for outbound emails, e.g. 'Acme Support'",
                        max_length=255,
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(
                        help_text="From address for outbound replies", max_length=254
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True,
                        help_text="Reply-To address (defaults to inbound_address if blank)",
                        max_length=254,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False if deactivated from dashboard",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Logo URL for HTML email header"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for links and accent elements, e.g. #2563eb",
                        max_length=7,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, help_text="Footer text for outbound emails"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("postmark", "Postmark"), ("sendgrid", "SendGrid")],
                        default="postmark",
                        help_text="Email provider for outbound delivery",
                        max_length=20,
                    ),
                ),
                (
                    "provider_api_key",
                    models.TextField(
                        blank=True,
                        help_text="API key for the selected email provider (encrypted at rest)",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Product this email channel is connected to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_channel_config",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Channel Configuration",
                "verbose_name_plural": "Email Channel Configurations",
            },
        ),
        migrations.CreateModel(
            name="EmailMessageMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="RFC 5322 Message-ID header value, e.g. <abc@domain>",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        help_text="Email address of the sender", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=500),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        help_text="Whether this message was received or sent",
                        max_length=10,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_mappings",
                        to="email_channel.emailchannelconfiguration",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mappings",
                        to="analytics.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message Mapping",
                "verbose_name_plural": "Email Message Mappings",
            },
        ),
        migrations.AddIndex(
            model_name="emailchannelconfiguration",
            index=models.Index(
                fields=["organization", "-created_at"], name="idx_email_cfg_org_created"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessagemapping",
            index=models.Index(
                fields=["config", "-created_at"], name="idx_email_msg_cfg_created"
            ),
        ),
    ]
