# Generated by Django 5.2.9 on 2026-03-23 19:18

import common.fields
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
import uuid
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0042_composable_mcp_sources"),
        ("users", "0008_add_usage_alert_last_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_id,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uris",
                    models.TextField(
                        blank=True, help_text="Allowed URIs list, space separated"
                    ),
                ),
                (
                    "post_logout_redirect_uris",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Allowed Post Logout URIs list, space separated",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("confidential", "Confidential"),
                            ("public", "Public"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "authorization_grant_type",
                    models.CharField(
                        choices=[
                            ("authorization-code", "Authorization code"),
                            (
                                "urn:ietf:params:oauth:grant-type:device_code",
                                "Device Code",
                            ),
                            ("implicit", "Implicit"),
                            ("password", "Resource owner password-based"),
                            ("client-credentials", "Client credentials"),
                            ("openid-hybrid", "OpenID connect hybrid"),
                        ],
                        max_length=44,
                    ),
                ),
                (
                    "client_secret",
                    oauth2_provider.models.ClientSecretField(
                        blank=True,
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_secret,
                        help_text="Hashed on Save. Copy it now if this is a new secret.",
                        max_length=255,
                    ),
                ),
                ("hash_client_secret", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("skip_authorization", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "algorithm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No OIDC support"),
                            ("RS256", "RSA with SHA-2 256"),
                            ("HS256", "HMAC with SHA-2 256"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "allowed_origins",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Allowed origins list to enable CORS, space separated",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this OAuth client is registered for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_oauth_apps",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP OAuth Application",
                "verbose_name_plural": "MCP OAuth Applications",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MCPGrant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("expires", models.DateTimeField()),
                ("redirect_uri", models.TextField()),
                ("scope", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "code_challenge",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "code_challenge_method",
                    models.CharField(
                        blank=True,
                        choices=[("plain", "plain"), ("S256", "S256")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("nonce", models.CharField(blank=True, default="", max_length=255)),
                ("claims", models.TextField(blank=True)),
                (
                    "external_user_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User claims from the customer's IdP",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MCPIDToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "jti",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="JWT Token ID",
                    ),
                ),
                ("expires", models.DateTimeField()),
                ("scope", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MCPAccessToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.TextField()),
                (
                    "token_checksum",
                    oauth2_provider.models.TokenChecksumField(
                        db_index=True, max_length=64, unique=True
                    ),
                ),
                ("expires", models.DateTimeField()),
                ("scope", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="User ID from the customer's IdP (e.g. 'sub' claim)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "external_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "external_display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_user_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full user claims from the customer's IdP",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_access_tokens",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "id_token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_token",
                        to=settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MCPRefreshToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
                (
                    "token_family",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("revoked", models.DateTimeField(null=True)),
                (
                    "access_token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refresh_token",
                        to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("token", "revoked")},
            },
        ),
        migrations.AddField(
            model_name="mcpaccesstoken",
            name="source_refresh_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refreshed_access_token",
                to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OAuthProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("oidc", "OpenID Connect"), ("oauth2", "OAuth 2.0")],
                        default="oidc",
                        max_length=20,
                    ),
                ),
                (
                    "issuer_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="OIDC issuer URL for auto-discovery",
                    ),
                ),
                (
                    "authorization_endpoint",
                    models.URLField(help_text="OAuth authorization endpoint URL"),
                ),
                (
                    "token_endpoint",
                    models.URLField(help_text="OAuth token endpoint URL"),
                ),
                (
                    "userinfo_endpoint",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="OIDC userinfo endpoint (optional if using id_token claims)",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="OAuth client ID registered with the IdP",
                        max_length=255,
                    ),
                ),
                (
                    "client_secret",
                    common.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="OAuth client secret (encrypted at rest)",
                    ),
                ),
                (
                    "scopes",
                    models.CharField(
                        default="openid email profile",
                        help_text="Space-separated scopes to request from the IdP",
                        max_length=500,
                    ),
                ),
                (
                    "user_id_claim",
                    models.CharField(
                        default="sub",
                        help_text="IdP claim that maps to user ID",
                        max_length=100,
                    ),
                ),
                (
                    "email_claim",
                    models.CharField(
                        default="email",
                        help_text="IdP claim that maps to email",
                        max_length=100,
                    ),
                ),
                (
                    "name_claim",
                    models.CharField(
                        default="name",
                        help_text="IdP claim that maps to display name",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether OAuth is required for MCP clients",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_provider",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Provider",
                "verbose_name_plural": "OAuth Providers",
            },
        ),
    ]
