// ============================================================================
// Automation Types
// ============================================================================

// --- Trigger Types (Analysis Tasks) ---
// These run automatically to detect content opportunities

export type TriggerType =
  | 'ticket_pattern_analysis'
  | 'search_gap_analysis'
  | 'chat_escalation_analysis'
  | 'changelog_monitoring'
  | 'feedback_analysis'
  | 'performance_analysis'
  | 'duplicate_detection'
  | 'relationship_extraction';

export type TriggerSchedule = 'hourly' | '6h' | 'daily' | 'weekly' | 'webhook' | 'threshold';

export type TriggerStatus = 'active' | 'paused' | 'requires_setup';

export interface TriggerDataSource {
  id: string;
  name: string;
  type: string; // 'zendesk', 'intercom', 'github', etc.
  isConnected: boolean;
}

export interface TriggerInfo {
  type: TriggerType;
  name: string;
  description: string;
  status: TriggerStatus;
  schedule: TriggerSchedule;
  dataSources: TriggerDataSource[];
  lastRunAt: string | null;
  nextRunAt: string | null;
  lastFindingsCount: number;
  requiresSetup?: string; // e.g., "Requires: AI assistant integration"
}

export interface TriggerRun {
  id: string;
  triggerType: TriggerType;
  triggerName: string;
  status: 'running' | 'completed' | 'failed';
  startedAt: string;
  completedAt: string | null;
  durationSeconds: number | null;
  itemsAnalyzed: number;
  findingsCount: number;
  findings: TriggerFinding[];
  errorMessage: string | null;
}

export interface TriggerFinding {
  id: string;
  type: 'article_opportunity' | 'update_needed' | 'seo_improvement' | 'duplicate_pair' | 'stale_content' | 'relationship_found';
  title: string;
  description: string;
  confidence: number; // 0-100
  suggestedAction: ActionType;
  metadata: Record<string, unknown>;
}

// --- Action Types (Execution Tasks) ---
// These execute when triggered by analysis

export type ActionCategory = 'content_creation' | 'content_updates' | 'content_organization' | 'content_maintenance';

export type ActionType =
  | 'generate_article'
  | 'generate_category'
  | 'generate_faq'
  | 'update_article_content'
  | 'refresh_screenshots'
  | 'update_seo_metadata'
  | 'add_related_links'
  | 'categorize_article'
  | 'suggest_tags'
  | 'link_related_articles'
  | 'merge_duplicates'
  | 'flag_for_review'
  | 'archive_article'
  | 'escalate_to_human'
  | 'link_knowledge_graph';

export interface ActionInfo {
  type: ActionType;
  category: ActionCategory;
  name: string;
  description: string;
  triggeredBy: TriggerType[];
  isAutomatic: boolean;
}

// --- Pending Actions (Generated by Triggers) ---

export interface PendingAction {
  id: string;
  actionType: ActionType;
  triggeredBy: TriggerType;
  triggerRunId: string;
  createdAt: string;
  title: string;
  description: string;
  status: 'pending' | 'approved' | 'rejected' | 'executed';
  confidence: number;
  metadata: Record<string, unknown>;
}

export interface PendingActionGroup {
  actionType: ActionType;
  actionName: string;
  count: number;
  triggerSources: string[]; // e.g., ["Ticket patterns (2)", "Search gaps (1)"]
}

// --- Legacy Task Types (for backwards compatibility) ---

export type TaskCategory = 'content_creation' | 'content_organization' | 'content_quality';

export type TaskType =
  | 'generate_article'
  | 'auto_update_article'
  | 'categorize_article'
  | 'link_articles'
  | 'suggest_tags'
  | 'detect_duplicates'
  | 'detect_staleness'
  | 'screenshot_refresh';

// --- Task Type Info ---

export interface TaskTypeInfo {
  type: TaskType;
  category: TaskCategory;
  name: string;
  description: string;
  autoTrigger: string;
  isAutoEnabled: boolean;
  lastRunAt: string | null;
  lastRunStatus: 'completed' | 'failed' | null;
}

export interface TaskCategoryInfo {
  id: TaskCategory;
  name: string;
  description: string;
  tasks: TaskTypeInfo[];
}

// --- Task Run (Activity) ---

export type TaskRunStatus = 'started' | 'completed' | 'failed' | 'cancelled';

export interface TaskRun {
  id: string;
  taskType: TaskType;
  taskName: string;
  status: TaskRunStatus;
  startedAt: string;
  completedAt: string | null;
  durationSeconds: number | null;
  itemsProcessed: number;
  suggestionsCreated: number;
  errorMessage: string | null;
  inputConfig: Record<string, unknown>;
  outputSummary: string;
}

// --- API Response Types ---

export interface TaskListResponse {
  categories: TaskCategoryInfo[];
}

export interface TaskActivityResponse {
  runs: TaskRun[];
  total: number;
  hasMore: boolean;
}

export interface RunTaskRequest {
  taskType: TaskType;
  config?: Record<string, unknown>;
}

export interface RunTaskResponse {
  runId: string;
  status: 'started';
  taskType: TaskType;
}

// --- Task Display Helpers ---

export const TASK_CATEGORY_LABELS: Record<TaskCategory, string> = {
  content_creation: 'Content Creation',
  content_organization: 'Content Organization',
  content_quality: 'Content Quality',
};

export const TASK_TYPE_LABELS: Record<TaskType, string> = {
  generate_article: 'Generate Article',
  auto_update_article: 'Auto-Update Article',
  categorize_article: 'Categorize Article',
  link_articles: 'Link Related Articles',
  suggest_tags: 'Suggest Tags',
  detect_duplicates: 'Detect Duplicates',
  detect_staleness: 'Detect Staleness',
  screenshot_refresh: 'Screenshot Refresh',
};

export const TASK_TYPE_DESCRIPTIONS: Record<TaskType, string> = {
  generate_article: 'Create articles from support tickets and queries',
  auto_update_article: 'Update articles based on product changes',
  categorize_article: 'Assign articles to appropriate categories',
  link_articles: 'Find and link related content',
  suggest_tags: 'Generate tag suggestions for articles',
  detect_duplicates: 'Find duplicate or overlapping articles',
  detect_staleness: 'Find articles that may be outdated',
  screenshot_refresh: 'Identify screenshots needing updates',
};

export const TASK_TYPE_TRIGGERS: Record<TaskType, string> = {
  generate_article: 'Pattern detected',
  auto_update_article: 'Changelog detected',
  categorize_article: 'New content',
  link_articles: 'New content',
  suggest_tags: 'New content',
  detect_duplicates: 'Scheduled',
  detect_staleness: 'Scheduled',
  screenshot_refresh: 'UI changelog',
};

export const TASK_CATEGORY_ORDER: TaskCategory[] = [
  'content_creation',
  'content_organization',
  'content_quality',
];

export const TASKS_BY_CATEGORY: Record<TaskCategory, TaskType[]> = {
  content_creation: ['generate_article', 'auto_update_article'],
  content_organization: ['categorize_article', 'link_articles', 'suggest_tags'],
  content_quality: ['detect_duplicates', 'detect_staleness', 'screenshot_refresh'],
};

// ============================================================================
// Trigger Display Helpers
// ============================================================================

export const TRIGGER_TYPE_LABELS: Record<TriggerType, string> = {
  ticket_pattern_analysis: 'Ticket Pattern Analysis',
  search_gap_analysis: 'Search Gap Analysis',
  chat_escalation_analysis: 'Chat Escalation Analysis',
  changelog_monitoring: 'Changelog Monitoring',
  feedback_analysis: 'Feedback Analysis',
  performance_analysis: 'Performance Analysis',
  duplicate_detection: 'Duplicate Detection',
  relationship_extraction: 'Knowledge Graph Discovery',
};

export const TRIGGER_TYPE_DESCRIPTIONS: Record<TriggerType, string> = {
  ticket_pattern_analysis: 'Scans support tickets to find recurring questions',
  search_gap_analysis: 'Finds searches with no or poor results',
  chat_escalation_analysis: 'Analyzes AI chat conversations that escalated to human support',
  changelog_monitoring: 'Watches for product changes that affect documentation',
  feedback_analysis: 'Analyzes negative feedback patterns on articles',
  performance_analysis: 'Identifies underperforming content by analytics',
  duplicate_detection: 'Scans for overlapping content between articles',
  relationship_extraction: 'Discovers semantic relationships between articles for the knowledge graph',
};

export const TRIGGER_DEFAULT_SCHEDULES: Record<TriggerType, TriggerSchedule> = {
  ticket_pattern_analysis: '6h',
  search_gap_analysis: 'daily',
  chat_escalation_analysis: 'daily',
  changelog_monitoring: 'webhook',
  feedback_analysis: 'daily',
  performance_analysis: 'weekly',
  duplicate_detection: 'weekly',
  relationship_extraction: 'weekly',
};

export const TRIGGER_INPUT_SOURCES: Record<TriggerType, string> = {
  ticket_pattern_analysis: 'Support tickets from connected sources',
  search_gap_analysis: 'Search queries + click-through data',
  chat_escalation_analysis: 'Chat transcripts marked as escalated',
  changelog_monitoring: 'GitHub releases, product changelog',
  feedback_analysis: 'Article feedback (helpful/not helpful votes)',
  performance_analysis: 'View counts, bounce rates, helpfulness scores',
  duplicate_detection: 'All published articles',
  relationship_extraction: 'All published articles in the help center',
};

export const TRIGGER_OUTPUT_ACTIONS: Record<TriggerType, ActionType[]> = {
  ticket_pattern_analysis: ['generate_article'],
  search_gap_analysis: ['generate_article', 'update_seo_metadata'],
  chat_escalation_analysis: ['generate_article'],
  changelog_monitoring: ['update_article_content', 'flag_for_review'],
  feedback_analysis: ['update_article_content', 'flag_for_review'],
  performance_analysis: ['update_article_content', 'archive_article'],
  duplicate_detection: ['merge_duplicates'],
  relationship_extraction: ['link_knowledge_graph'],
};

// ============================================================================
// Action Display Helpers
// ============================================================================

export const ACTION_TYPE_LABELS: Record<ActionType, string> = {
  generate_article: 'Generate Article Draft',
  generate_category: 'Generate Category',
  generate_faq: 'Generate FAQ Section',
  update_article_content: 'Update Article Content',
  refresh_screenshots: 'Refresh Screenshots',
  update_seo_metadata: 'Update SEO Metadata',
  add_related_links: 'Add Related Links',
  categorize_article: 'Categorize Article',
  suggest_tags: 'Suggest Tags',
  link_related_articles: 'Link Related Articles',
  merge_duplicates: 'Merge Duplicates',
  flag_for_review: 'Flag for Review',
  archive_article: 'Archive Article',
  escalate_to_human: 'Escalate to Human',
  link_knowledge_graph: 'Knowledge Graph Links',
};

export const ACTION_CATEGORY_LABELS: Record<ActionCategory, string> = {
  content_creation: 'Content Creation',
  content_updates: 'Content Updates',
  content_organization: 'Content Organization',
  content_maintenance: 'Content Maintenance',
};

export const ACTIONS_BY_CATEGORY: Record<ActionCategory, ActionType[]> = {
  content_creation: ['generate_article', 'generate_category', 'generate_faq'],
  content_updates: ['update_article_content', 'refresh_screenshots', 'update_seo_metadata', 'add_related_links'],
  content_organization: ['categorize_article', 'suggest_tags', 'link_related_articles', 'merge_duplicates', 'link_knowledge_graph'],
  content_maintenance: ['flag_for_review', 'archive_article', 'escalate_to_human'],
};

// ============================================================================
// Trigger API Response Types
// ============================================================================

export interface TriggerListResponse {
  triggers: TriggerInfo[];
}

export interface TriggerActivityResponse {
  runs: TriggerRun[];
  total: number;
  hasMore: boolean;
}

export interface PendingActionsResponse {
  groups: PendingActionGroup[];
  total: number;
}

export interface RunTriggerRequest {
  triggerType: TriggerType;
}

export interface RunTriggerResponse {
  runId: string;
  status: 'started';
  triggerType: TriggerType;
}

// ============================================================================
// Knowledge Graph Relationship Types
// ============================================================================

export interface ArticleSummary {
  id: string;
  title: string;
  slug: string;
}

export interface PendingRelationship {
  id: string;
  sourceArticle: ArticleSummary;
  targetArticle: ArticleSummary;
  relationshipDescription: string;
  inverseDescription: string;
  isSymmetric: boolean;
  factStatement: string;
  confidence: number;
  reasoning: string;
  createdAt: string;
}

export interface PendingRelationshipsResponse {
  relationships: PendingRelationship[];
  total: number;
  hasMore: boolean;
}

// Full Relationship type (includes all statuses, not just pending)
export type RelationshipStatus = 'pending' | 'active' | 'rejected' | 'archived';
export type RelationshipCreatedByType = 'librarian_agent' | 'human' | 'import';

export interface Relationship {
  id: string;
  organization: string;
  sourceArticle: ArticleSummary;
  targetArticle: ArticleSummary;
  relationshipDescription: string;
  inverseDescription: string | null;
  isSymmetric: boolean;
  factStatement: string;
  createdByType: RelationshipCreatedByType;
  confidence: number;
  reasoning: string | null;
  status: RelationshipStatus;
  reviewedBy: string | null;
  reviewedByName: string | null;
  reviewedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RelationshipsListResponse {
  results: Relationship[];
  count: number;
  next: string | null;
  previous: string | null;
}

export interface RelationshipFilters {
  status?: RelationshipStatus;
  createdByType?: RelationshipCreatedByType;
  sourceArticle?: string;
  targetArticle?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
}

export interface CreateRelationshipRequest {
  sourceArticle: string;
  targetArticle: string;
  relationshipDescription: string;
  inverseDescription?: string;
  isSymmetric?: boolean;
  factStatement: string;
}

export interface UpdateRelationshipRequest {
  relationshipDescription?: string;
  inverseDescription?: string;
  isSymmetric?: boolean;
  factStatement?: string;
  status?: RelationshipStatus;
}

// Knowledge Graph Visualization
export interface KnowledgeGraphNode {
  id: string;
  slug: string;
  title: string;
}

export interface KnowledgeGraphEdge {
  id: string;
  source: string;
  target: string;
  label: string;
  inverseLabel: string | null;
  isSymmetric: boolean;
  confidence: number;
}

export interface KnowledgeGraph {
  nodes: KnowledgeGraphNode[];
  edges: KnowledgeGraphEdge[];
}

// Knowledge Graph Stats
export interface RelationshipStats {
  totalRelationships: number;
  byStatus: {
    pending: number;
    active: number;
    rejected: number;
    archived: number;
  };
  bySource: {
    librarianAgent: number;
    human: number;
    import: number;
  };
  uniqueArticlesInGraph: number;
  avgConfidence: number;
}

// ============================================================================
// Automation Workflow Types
// ============================================================================

// Source categories that triggers can depend on
export type SourceCategory = 'ticket' | 'changelog' | 'chat' | 'built_in';

// Source requirement for a trigger
export interface SourceRequirement {
  category: SourceCategory;
  label: string;              // e.g., "Zendesk, Intercom, or other ticket source"
  setupPath: string | null;   // e.g., "/admin/sources/external", null if built-in
}

// Map triggers to their required sources
export const TRIGGER_SOURCE_REQUIREMENTS: Record<TriggerType, SourceRequirement> = {
  ticket_pattern_analysis: {
    category: 'ticket',
    label: 'ticket source (Zendesk, Intercom)',
    setupPath: '/sources/external',
  },
  search_gap_analysis: {
    category: 'built_in',
    label: 'Search analytics',
    setupPath: null,
  },
  chat_escalation_analysis: {
    category: 'chat',
    label: 'AI Assistant',
    setupPath: '/settings',
  },
  changelog_monitoring: {
    category: 'changelog',
    label: 'GitHub or changelog source',
    setupPath: '/sources/external',
  },
  feedback_analysis: {
    category: 'built_in',
    label: 'Article feedback',
    setupPath: null,
  },
  performance_analysis: {
    category: 'built_in',
    label: 'Analytics',
    setupPath: null,
  },
  duplicate_detection: {
    category: 'built_in',
    label: 'Published articles',
    setupPath: null,
  },
  relationship_extraction: {
    category: 'built_in',
    label: 'Published articles',
    setupPath: null,
  },
};

// Automation status
export type AutomationStatus = 'active' | 'paused' | 'needs_setup';

// Automation definition (pre-defined workflow)
export interface AutomationDefinition {
  id: string;
  name: string;
  description: string;
  triggers: TriggerType[];
  tasks: TaskType[];
}

// Runtime automation state (definition + live status)
export interface AutomationInfo {
  definition: AutomationDefinition;
  status: AutomationStatus;
  lastRunAt: string | null;
  nextRunAt: string | null;
  pendingCount: number;
  triggerStatuses: {
    triggerType: TriggerType;
    status: TriggerStatus;
    schedule: TriggerSchedule;
    lastRunAt: string | null;
  }[];
  missingRequirements?: {
    label: string;
    setupPath: string;
  }[];
}

// API response
export interface AutomationListResponse {
  automations: AutomationInfo[];
}

// ============================================================================
// Default Automations
// ============================================================================

export const DEFAULT_AUTOMATIONS: AutomationDefinition[] = [
  {
    id: 'new-article-generation',
    name: 'New Article Generation',
    description: 'Create articles from customer questions',
    triggers: ['ticket_pattern_analysis', 'search_gap_analysis', 'chat_escalation_analysis'],
    tasks: ['generate_article', 'categorize_article', 'link_articles'],
  },
  {
    id: 'content-freshness',
    name: 'Content Freshness',
    description: 'Keep documentation current with product changes',
    triggers: ['changelog_monitoring', 'feedback_analysis'],
    tasks: ['detect_staleness', 'auto_update_article'],
  },
  {
    id: 'content-quality',
    name: 'Content Quality',
    description: 'Maintain quality and remove duplicates',
    triggers: ['performance_analysis', 'duplicate_detection'],
    tasks: ['detect_duplicates', 'detect_staleness'],
  },
  {
    id: 'knowledge-organization',
    name: 'Knowledge Organization',
    description: 'Build relationships and improve discoverability',
    triggers: ['relationship_extraction'],
    tasks: ['link_articles', 'suggest_tags'],
  },
];
