# Generated by Django 5.2.9 on 2025-12-17 18:09
#
# Adds billing_email and onboarding_current_step fields to Organization model.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for billing communications",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="onboarding_current_step",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Current step in the onboarding wizard (1-7)"
            ),
        ),
    ]
