# Generated by Django 5.2.9 on 2026-01-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_default_language'),
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_selected_product',
            field=models.ForeignKey(blank=True, help_text="User's last selected product (restored on login)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_selected_by_users', to='products.product'),
        ),
    ]
