# Generated by Django 5.2.9 on 2026-02-03 18:49

from django.db import migrations, models


def migrate_starter_to_hobby(apps, schema_editor):
    """Convert any existing 'starter' plans to 'hobby'."""
    Organization = apps.get_model('users', 'Organization')
    Organization.objects.filter(plan='starter').update(plan='hobby')


def migrate_hobby_to_starter(apps, schema_editor):
    """Reverse migration: convert 'hobby' back to 'starter'."""
    Organization = apps.get_model('users', 'Organization')
    Organization.objects.filter(plan='hobby').update(plan='starter')


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_selected_product"),
    ]

    operations = [
        # First, migrate data before changing choices
        migrations.RunPython(migrate_starter_to_hobby, migrate_hobby_to_starter),
        # Then alter the field choices
        migrations.AlterField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("hobby", "Hobby"),
                    ("pro", "Pro"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=50,
            ),
        ),
    ]
