# Generated by Django 5.2.9 on 2026-02-09 23:23

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_update_plan_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.UUIDField(
                default=uuid_utils.compat.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
