# Generated by Django 5.2.9 on 2026-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the CEO welcome email was sent to this user', null=True),
        ),
    ]
