# Generated by Django 5.2.9 on 2026-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_welcome_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Customer ID (cus_...)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Current Stripe Price ID for the active subscription",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Active Stripe Subscription ID (sub_...)",
                max_length=255,
                null=True,
            ),
        ),
    ]
