# Generated by Django 5.2.9 on 2026-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_organization_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="usage_alert_last_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Last usage threshold percentage notified (80 or 100). Reset each billing period.",
                null=True,
            ),
        ),
    ]
