# Generated by Django 5.2.9 on 2026-02-12 17:42

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentScoreReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "url",
                    models.URLField(
                        help_text="Full URL that was scanned", max_length=2048
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Extracted domain for caching/aggregation",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.IntegerField(blank=True, null=True)),
                ("discovery_score", models.IntegerField(blank=True, null=True)),
                ("readability_score", models.IntegerField(blank=True, null=True)),
                ("interactability_score", models.IntegerField(blank=True, null=True)),
                ("permissions_score", models.IntegerField(blank=True, null=True)),
                ("accessibility_score", models.IntegerField(blank=True, null=True)),
                ("webmcp_score", models.IntegerField(blank=True, null=True)),
                (
                    "raw_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Main page HTML from httpx (pre-JS)",
                    ),
                ),
                (
                    "page_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Meta tags, title, OG tags extracted from HTML",
                    ),
                ),
                (
                    "probe_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured results from all HTTP probe requests",
                    ),
                ),
                (
                    "rendered_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full HTML after JS execution (Playwright)",
                    ),
                ),
                (
                    "accessibility_tree",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Playwright accessibility tree snapshot",
                    ),
                ),
                (
                    "axe_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="axe-core accessibility audit results",
                    ),
                ),
                (
                    "webmcp_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="WebMCP detection results from JS execution",
                    ),
                ),
                (
                    "forms_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Enumerated forms with label analysis",
                    ),
                ),
                (
                    "captcha_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="CAPTCHA detection results"
                    ),
                ),
                (
                    "screenshot_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to stored full-page screenshot",
                        max_length=2048,
                    ),
                ),
                (
                    "datacenter_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Issues found from data center access perspective",
                    ),
                ),
                ("html_token_count", models.IntegerField(blank=True, null=True)),
                ("markdown_token_count", models.IntegerField(blank=True, null=True)),
                ("content_token_count", models.IntegerField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if status is 'failed'",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Optional email for follow-up",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Score Report",
                "verbose_name_plural": "Agent Score Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "-created_at"], name="idx_asr_domain_created"
                    ),
                    models.Index(fields=["status"], name="idx_asr_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentScoreCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("readability", "Readability"),
                            ("interactability", "Interactability"),
                            ("permissions", "Permissions"),
                            ("accessibility", "Accessibility"),
                            ("webmcp", "WebMCP"),
                        ],
                        help_text="Scoring category this check belongs to",
                        max_length=30,
                    ),
                ),
                (
                    "check_name",
                    models.CharField(
                        help_text="Machine-readable check identifier (e.g. 'llms_txt_present')",
                        max_length=100,
                    ),
                ),
                (
                    "check_label",
                    models.CharField(
                        help_text="Human-readable check description (e.g. 'Has /llms.txt')",
                        max_length=200,
                    ),
                ),
                ("passed", models.BooleanField(help_text="Whether the check passed")),
                (
                    "score",
                    models.IntegerField(
                        help_text="Score from 0-100 for this individual check"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(help_text="Relative weight within its category"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Check-specific structured data",
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Actionable recommendation if check didn't pass",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Parent report this check belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="agent_score.agentscorereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Score Check",
                "verbose_name_plural": "Agent Score Checks",
                "ordering": ["category", "check_name"],
                "indexes": [
                    models.Index(
                        fields=["report", "category"], name="idx_asc_report_cat"
                    )
                ],
            },
        ),
    ]
