# Generated by Django 5.2.9 on 2026-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="content_signal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Content-Signal header value (e.g. 'ai-train=yes, search=yes, ai-input=yes')",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="supports_markdown_negotiation",
            field=models.BooleanField(
                default=False,
                help_text="Site responds with text/markdown when Accept: text/markdown is sent",
            ),
        ),
    ]
