# Generated by Django 5.2.9 on 2026-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0002_agentscorereport_content_signal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="signup_test_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed results from the Stagehand signup attempt",
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="signup_test_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether the signup test was requested for this scan",
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="signup_test_score",
            field=models.IntegerField(
                blank=True,
                help_text="Signup test score 0-100 (null if not enabled or not yet scored)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentscorecheck",
            name="category",
            field=models.CharField(
                choices=[
                    ("discovery", "Discovery"),
                    ("readability", "Readability"),
                    ("interactability", "Interactability"),
                    ("permissions", "Permissions"),
                    ("accessibility", "Accessibility"),
                    ("webmcp", "WebMCP"),
                    ("signup_test", "Signup Test"),
                ],
                help_text="Scoring category this check belongs to",
                max_length=30,
            ),
        ),
    ]
