# Generated by Django 5.2.9 on 2026-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0003_signup_test_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="completed_layers",
            field=models.IntegerField(
                default=0,
                help_text="Atomic counter for fan-in coordination. Incremented by each parallel task (http_probes, browser_analysis). When it reaches 2, the analyze-and-score task is triggered.",
            ),
        ),
    ]
