# Generated by Django 5.2.9 on 2026-02-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0004_add_completed_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="scan_notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of notes/warnings generated during the scan. Each entry: {type, category, title, detail}",
            ),
        ),
    ]
