# Generated by Django 5.2.9 on 2026-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0006_consolidate_to_4_categories"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentscorereport",
            index=models.Index(
                fields=["domain", "status", "signup_test_enabled", "-created_at"],
                name="idx_asr_cache_lookup",
            ),
        ),
    ]
