# Generated by Django 5.2.9 on 2026-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0007_add_cache_lookup_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="signup_test_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short status message for the signup test progress UI. Updated at each phase: navigating, filling form, submitting, classifying.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agentscorereport",
            name="completed_layers",
            field=models.IntegerField(
                default=0,
                help_text="Atomic counter for fan-in coordination. Incremented by each parallel task (http_probes, browser_analysis, and optionally signup_test). When it reaches the required count (2 or 3), the analyze-and-score task is triggered.",
            ),
        ),
    ]
