# Generated by Django 5.2.9 on 2026-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0008_add_signup_test_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorecheck",
            name="status",
            field=models.CharField(
                choices=[("evaluated", "Evaluated"), ("dnf", "Did Not Finish")],
                default="evaluated",
                help_text="Whether this check ran successfully or could not be evaluated",
                max_length=20,
            ),
        ),
    ]
