# Generated by Django 5.2.9 on 2026-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0009_add_check_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="redirect_chain",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of redirect hops: [{status_code, from_url, to_url}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="resolved_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Final URL after following all redirects from the homepage",
                max_length=2048,
            ),
        ),
    ]
