# Generated by Django 5.2.9 on 2026-02-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0010_add_redirect_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="category_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Category score map, e.g. {"content": 85, "interaction": 72, "webmcp": null}. New reports write here; the legacy per-category columns below are kept for backward compatibility with old reports.',
            ),
        ),
    ]
