# Generated by Django 5.2.9 on 2026-02-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0011_add_category_scores_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="openclaw_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full results from the OpenClaw agent test: score, summary, what_worked, what_didnt, tasks_tried, mcp_found, etc.",
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="openclaw_test_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the OpenClaw agent experience test was requested for this scan",
            ),
        ),
        migrations.AddField(
            model_name="agentscorereport",
            name="openclaw_test_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short status message for the OpenClaw test progress UI. Updated at each phase: starting, browsing, testing, scoring.",
                max_length=100,
            ),
        ),
    ]
