# Generated by Django 5.2.9 on 2026-02-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0012_openclaw_test_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentscorecheck",
            name="category",
            field=models.CharField(
                choices=[
                    ("content", "Content"),
                    ("interaction", "Interaction"),
                    ("webmcp", "WebMCP"),
                    ("signup_test", "Signup Test"),
                    ("openclaw", "Agent Experience"),
                ],
                help_text="Scoring category this check belongs to",
                max_length=30,
            ),
        ),
    ]
