# Generated by Django 5.2.9 on 2026-02-14 22:44

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0013_add_openclaw_check_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentScoreLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.CharField(
                        help_text="Workflow phase that produced this entry, e.g. 'http_probes', 'browser_analysis', 'signup_test', 'openclaw_test', 'analyze_and_score', 'finalize'",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        help_text="Severity level for display styling",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Human-readable description of what happened",
                        max_length=500,
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Expandable structured data (URLs, status codes, errors, etc.)",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Parent report this log entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="agent_score.agentscorereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Score Log Entry",
                "verbose_name_plural": "Agent Score Log Entries",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["report", "created_at"], name="idx_aslog_report_created"
                    )
                ],
            },
        ),
    ]
