# Generated by Django 5.2.9 on 2026-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0014_add_log_entry_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentscorecheck",
            name="category",
            field=models.CharField(
                choices=[
                    ("rules", "Rules"),
                    ("webmcp", "WebMCP"),
                    ("signup_test", "Signup Test"),
                    ("openclaw", "Agent Experience"),
                ],
                help_text="Scoring category this check belongs to",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="agentscorereport",
            name="category_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Category score map, e.g. {"rules": 85, "openclaw": 72, "signup_test": 80, "webmcp": null}. New reports write here; the legacy per-category columns below are kept for backward compatibility with old reports.',
            ),
        ),
    ]
