# Generated by Django 5.2.9 on 2026-02-15 17:30

from django.db import migrations


def rename_content_interaction_to_rules(apps, schema_editor):
    """Rename content and interaction categories to rules in existing checks."""
    AgentScoreCheck = apps.get_model("agent_score", "AgentScoreCheck")
    AgentScoreCheck.objects.filter(category="content").update(category="rules")
    AgentScoreCheck.objects.filter(category="interaction").update(category="rules")


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0015_alter_agentscorecheck_category_and_more"),
    ]

    operations = [
        migrations.RunPython(
            rename_content_interaction_to_rules,
            migrations.RunPython.noop,
        ),
    ]
