# Generated by Django 5.2.9 on 2026-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0016_rename_content_interaction_to_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentscorereport",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the score report email was sent (null = not yet sent)",
                null=True,
            ),
        ),
    ]
