# Generated by Django 5.2.9 on 2026-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_score", "0017_add_email_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentscorecheck",
            name="category",
            field=models.CharField(
                choices=[
                    ("rules", "Rules"),
                    ("webmcp", "WebMCP"),
                    ("signup_test", "Browserbase Test"),
                    ("openclaw", "Openclaw Experience"),
                ],
                help_text="Scoring category this check belongs to",
                max_length=30,
            ),
        ),
    ]
