# Generated by Django 5.2.9 on 2026-03-10 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0008_add_usage_alert_last_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusResponseGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Number of bonus responses in this grant"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this grant expires (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True,
                        help_text="Why this grant was given (e.g. 'Early adopter bonus')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who granted this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_response_grants",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus Response Grant",
                "verbose_name_plural": "Bonus Response Grants",
                "db_table": "billing_bonus_response_grant",
                "ordering": ["-created_at"],
            },
        ),
    ]
