# Generated by Django 5.2.9 on 2026-01-12 19:32

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this source", max_length=200
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("help_center", "Help Center"),
                            ("marketing_site", "Marketing Site"),
                            ("snippets", "Custom Snippets"),
                        ],
                        db_index=True,
                        help_text="Type of content source",
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Root URL to crawl (blank for snippets)",
                        max_length=2000,
                    ),
                ),
                (
                    "crawl_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Crawl settings: max_pages, include_paths, exclude_paths, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("syncing", "Syncing"),
                            ("error", "Error"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current sync status",
                        max_length=20,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful sync time", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if status is 'error'",
                    ),
                ),
                (
                    "item_count",
                    models.IntegerField(
                        default=0, help_text="Number of items from this source"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this source belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "db_table": "knowledge_source",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("page", "Web Page"), ("snippet", "Snippet")],
                        db_index=True,
                        help_text="Type of content item",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier (URL hash for pages)",
                        max_length=255,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Source URL for pages", max_length=2000
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the content", max_length=500),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        help_text="Original content (markdown/HTML from crawl or user input)",
                    ),
                ),
                (
                    "optimized_content",
                    models.TextField(
                        blank=True, help_text="LLM-cleaned content for RAG indexing"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, help_text="Short summary/description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Processing status",
                        max_length=20,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="MD5 hash of raw_content for change detection",
                        max_length=32,
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this item was last indexed",
                        null=True,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if processing failed",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this item is available to the Product Assistant",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific data: {word_count, priority, etc.}",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="users.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="knowledge.knowledgesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Item",
                "verbose_name_plural": "Knowledge Items",
                "db_table": "knowledge_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Chunk title (usually the heading)", max_length=500
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual text content of this chunk"),
                ),
                (
                    "heading_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Heading hierarchy: ['H1 Title', 'H2 Section', 'H3 Subsection']",
                        size=None,
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        default=0, help_text="Position of this chunk within the item"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding for semantic search",
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Model used to generate embedding",
                        max_length=100,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="MD5 hash of content for staleness detection",
                        max_length=32,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="users.organization",
                    ),
                ),
                (
                    "knowledge_item",
                    models.ForeignKey(
                        help_text="Item this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Chunk",
                "verbose_name_plural": "Knowledge Chunks",
                "db_table": "knowledge_chunk",
                "ordering": ["knowledge_item", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_item", "chunk_index"],
                        name="knowledge_c_knowled_4a0edb_idx",
                    ),
                    models.Index(
                        fields=["organization"], name="knowledge_c_organiz_87f1f2_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="knowledge_c_content_c6d808_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["organization", "source_type"],
                name="knowledge_s_organiz_203089_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["organization", "status"], name="knowledge_s_organiz_164485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["organization", "status", "is_active"],
                name="knowledge_i_organiz_9187ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["source", "item_type"], name="knowledge_i_source__de84cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["source", "status"], name="knowledge_i_source__459733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["content_hash"], name="knowledge_i_content_24cdc0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeitem",
            unique_together={("source", "external_id")},
        ),
    ]
