# Generated by Django 5.2.9 on 2026-01-13 05:16
# Modified to add PostgreSQL trigger for auto-updating search vector

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        # Enable pg_trgm extension for fuzzy matching (idempotent)
        TrigramExtension(),

        # Add search_vector field
        migrations.AddField(
            model_name="knowledgeitem",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True,
                help_text="Pre-computed tsvector for full-text search (title + optimized_content)",
                null=True,
            ),
        ),

        # Add GIN index on search_vector
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="knowledge_item_search_gin"
            ),
        ),

        # Create PostgreSQL function to build search vector
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION build_knowledgeitem_vector(
                p_title TEXT,
                p_optimized_content TEXT
            ) RETURNS tsvector AS $$
            DECLARE
                v_truncated_content TEXT;
            BEGIN
                -- Truncate content to avoid 1MB tsvector limit
                v_truncated_content := COALESCE(LEFT(p_optimized_content, 500000), '');
                
                RETURN 
                    setweight(to_tsvector('english', COALESCE(p_title, '')), 'A') ||
                    setweight(to_tsvector('english', v_truncated_content), 'B');
            END;
            $$ LANGUAGE plpgsql IMMUTABLE;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS build_knowledgeitem_vector(TEXT, TEXT);"
        ),

        # Create trigger function to auto-update vector on INSERT/UPDATE
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_knowledgeitem_vector()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.search_vector := build_knowledgeitem_vector(
                    NEW.title,
                    NEW.optimized_content
                );
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS knowledgeitem_update_vector ON knowledge_item;
            CREATE TRIGGER knowledgeitem_update_vector
            BEFORE INSERT OR UPDATE OF title, optimized_content ON knowledge_item
            FOR EACH ROW
            EXECUTE FUNCTION update_knowledgeitem_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS knowledgeitem_update_vector ON knowledge_item;
            DROP FUNCTION IF EXISTS update_knowledgeitem_vector();
            """
        ),

        # Create trigram index on title for fuzzy matching
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS knowledge_item_title_trgm 
            ON knowledge_item USING GIN(title gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS knowledge_item_title_trgm;"
        ),

        # Backfill existing indexed records
        migrations.RunSQL(
            sql="""
            UPDATE knowledge_item
            SET search_vector = build_knowledgeitem_vector(title, optimized_content)
            WHERE search_vector IS NULL AND status = 'indexed';
            """,
            reverse_sql="-- No reverse needed for backfill"
        ),
    ]
