# Generated by Django 5.2.9 on 2026-01-13 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_add_search_vector"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeSyncHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("full", "Full"), ("incremental", "Incremental")],
                        default="full",
                        help_text="Type of sync operation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the sync",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the sync started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the sync completed", null=True
                    ),
                ),
                (
                    "items_synced",
                    models.IntegerField(default=0, help_text="Total items processed"),
                ),
                (
                    "items_created",
                    models.IntegerField(default=0, help_text="New items created"),
                ),
                (
                    "items_updated",
                    models.IntegerField(default=0, help_text="Existing items updated"),
                ),
                (
                    "items_failed",
                    models.IntegerField(
                        default=0, help_text="Items that failed to process"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error message if sync failed"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this sync belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sync_history",
                        to="users.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source this sync belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_history",
                        to="knowledge.knowledgesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Sync History",
                "verbose_name_plural": "Knowledge Sync History",
                "db_table": "knowledge_sync_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="knowledge_s_source__1a5fd3_idx",
                    ),
                    models.Index(
                        fields=["source", "-created_at"],
                        name="knowledge_s_source__99cdee_idx",
                    ),
                ],
            },
        ),
    ]
