# Generated by Django 5.2.9 on 2026-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_sync_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='connection_config',
            field=models.JSONField(blank=True, default=dict, help_text='Connection settings for integrations and cloud storage'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='source_type',
            field=models.CharField(choices=[('help_center', 'Help Center'), ('marketing_site', 'Marketing Site'), ('snippets', 'Custom Snippets'), ('integration', 'Integration'), ('cloud_storage', 'Cloud Storage'), ('document_upload', 'Document Upload')], db_index=True, help_text='Type of content source', max_length=50),
        ),
    ]
