# Generated by Django 5.2.9 on 2026-01-13 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_rename_analytics_a_organiz_902676_idx_analytics_a_organiz_02c3a4_idx_and_more"),
        ("knowledge", "0003_add_sync_history"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState because connection_config column may already exist
        # from a previous migration (0004_knowledgesource_connection_config_and_more on dev)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="knowledgesource",
                    name="connection_config",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connection settings for integrations and cloud storage",
                    ),
                ),
            ],
            database_operations=[],  # Column already exists in DB
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("help_center", "Help Center"),
                    ("marketing_site", "Marketing Site"),
                    ("snippets", "Custom Snippets"),
                    ("integration", "Integration"),
                    ("cloud_storage", "Cloud Storage"),
                    ("document_upload", "Document Upload"),
                ],
                db_index=True,
                help_text="Type of content source",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Correction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_question",
                    models.TextField(
                        blank=True,
                        help_text="The user's question that led to the incorrect response",
                    ),
                ),
                (
                    "original_response",
                    models.TextField(
                        blank=True, help_text="The AI's original (incorrect) response"
                    ),
                ),
                (
                    "user_correction_notes",
                    models.TextField(
                        help_text="What the user said was wrong and what's correct"
                    ),
                ),
                (
                    "processed_title",
                    models.CharField(
                        blank=True,
                        help_text="AI-generated title for the correction snippet",
                        max_length=500,
                    ),
                ),
                (
                    "processed_content",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated standardized correction content",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("indexed", "Indexed in Knowledge Base"),
                            ("failed", "Processing Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Processing status of this correction",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if processing failed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this correction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_item",
                    models.OneToOneField(
                        blank=True,
                        help_text="The snippet created from this correction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction",
                        to="knowledge.knowledgeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this correction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="users.organization",
                    ),
                ),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The conversation this correction came from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="analytics.chatconversation",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assistant message being corrected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="analytics.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correction",
                "verbose_name_plural": "Corrections",
                "db_table": "knowledge_correction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="knowledge_c_organiz_1cc176_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="knowledge_c_organiz_9d9ea1_idx",
                    ),
                    models.Index(
                        fields=["source_conversation"],
                        name="knowledge_c_source__39f8be_idx",
                    ),
                ],
            },
        ),
    ]
