# Generated by Django 5.2.9 on 2026-01-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledgesource_connection_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='source_type',
            field=models.CharField(choices=[('help_center', 'Help Center'), ('marketing_site', 'Marketing Site'), ('website_crawl', 'Website Crawl'), ('snippets', 'Custom Snippets'), ('integration', 'Integration'), ('cloud_storage', 'Cloud Storage'), ('document_upload', 'Document Upload')], db_index=True, help_text='Type of content source', max_length=50),
        ),
    ]
