# Generated by Django 5.2.9 on 2026-01-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_add_correction_model'),
        ('knowledge', '0005_alter_knowledgesource_source_type'),
    ]

    operations = [
    ]
