# Generated by Django 5.2.9 on 2026-01-15
# Phase 2: Enhanced corrections with reasoning support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_add_images_to_chatmessage"),
    ]

    operations = [
        # Add correction_type field
        migrations.AddField(
            model_name="correction",
            name="correction_type",
            field=models.CharField(
                choices=[
                    ("response", "Final Response"),
                    ("reasoning", "Reasoning Step"),
                    ("source", "Source Selection"),
                    ("search", "Search Strategy"),
                ],
                db_index=True,
                default="response",
                help_text="What aspect of the response is being corrected",
                max_length=20,
            ),
        ),
        # Add reasoning step tracking fields
        migrations.AddField(
            model_name="correction",
            name="reasoning_step_index",
            field=models.IntegerField(
                blank=True,
                help_text="Index of the reasoning step being corrected (0-based)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="reasoning_step_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of reasoning step: decision, search, source_eval, etc.",
                max_length=20,
            ),
        ),
        # Add reasoning trace capture fields
        migrations.AddField(
            model_name="correction",
            name="full_reasoning_trace",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Full reasoning trace at time of correction",
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="original_reasoning_step",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The specific reasoning step being corrected",
            ),
        ),
        # Add type-specific correction data fields
        migrations.AddField(
            model_name="correction",
            name="correct_reasoning",
            field=models.TextField(
                blank=True,
                help_text="What the agent SHOULD have thought/done at this step",
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="correct_search_query",
            field=models.CharField(
                blank=True,
                help_text="For search corrections: what query should have been used",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="correct_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For source corrections: which sources should have been prioritized",
            ),
        ),
        # Add index for organization + correction_type
        migrations.AddIndex(
            model_name="correction",
            index=models.Index(
                fields=["organization", "correction_type"],
                name="knowledge_c_organiz_type_idx",
            ),
        ),
    ]
