# Generated by Django 5.2.9 on 2026-01-16 00:07

import apps.knowledge.models.pending_upload
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0008_correction_reasoning_fields"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename as uploaded by user",
                        max_length=255,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path in cloud storage: pending/{org_id}/{upload_id}/{filename}",
                        max_length=500,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MIME type of the file",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        default=apps.knowledge.models.pending_upload.default_expiry,
                        help_text="When this pending upload expires and should be cleaned up",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this upload belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_uploads",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Upload",
                "verbose_name_plural": "Pending Uploads",
                "db_table": "knowledge_pending_upload",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "expires_at"],
                        name="knowledge_p_organiz_d78692_idx",
                    )
                ],
            },
        ),
    ]
