# Generated by Django 5.2.9 on 2026-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0009_add_pending_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeitem",
            name="processing_error",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Error message if processing failed",
                null=True,
            ),
        ),
    ]
