# Generated by Django 5.2.9 on 2026-01-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0010_allow_null_processing_error"),
        ("products", "0015_add_default_language"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgechunk",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product this chunk belongs to (denormalized from item.source)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_chunks",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product this item belongs to (denormalized from source)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product this source belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_sources",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["product"], name="knowledge_c_product_e8e507_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeitem",
            index=models.Index(
                fields=["product", "status", "is_active"],
                name="knowledge_i_product_3c0758_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["product", "source_type"], name="knowledge_s_product_6fb530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["product", "status"], name="knowledge_s_product_415f30_idx"
            ),
        ),
    ]
