# Generated by Django 5.2.9 on 2026-01-23 17:49

from django.db import migrations


def backfill_product_on_sources(apps, schema_editor):
    """
    Backfill product on KnowledgeSource from organization's default product.
    """
    KnowledgeSource = apps.get_model('knowledge', 'KnowledgeSource')
    Product = apps.get_model('products', 'Product')

    # Get all sources without a product
    sources_without_product = KnowledgeSource.objects.filter(product__isnull=True)

    for source in sources_without_product:
        # Get the default product for this organization
        default_product = Product.objects.filter(
            organization_id=source.organization_id,
            is_default=True
        ).first()

        if default_product:
            source.product = default_product
            source.save(update_fields=['product'])


def backfill_product_on_items(apps, schema_editor):
    """
    Backfill product on KnowledgeItem from source's product.
    """
    KnowledgeItem = apps.get_model('knowledge', 'KnowledgeItem')

    # Get all items without a product
    items_without_product = KnowledgeItem.objects.filter(
        product__isnull=True
    ).select_related('source')

    for item in items_without_product:
        if item.source and item.source.product_id:
            item.product_id = item.source.product_id
            item.save(update_fields=['product'])


def backfill_product_on_chunks(apps, schema_editor):
    """
    Backfill product on KnowledgeChunk from item's product.
    """
    KnowledgeChunk = apps.get_model('knowledge', 'KnowledgeChunk')

    # Get all chunks without a product
    chunks_without_product = KnowledgeChunk.objects.filter(
        product__isnull=True
    ).select_related('knowledge_item')

    for chunk in chunks_without_product:
        if chunk.knowledge_item and chunk.knowledge_item.product_id:
            chunk.product_id = chunk.knowledge_item.product_id
            chunk.save(update_fields=['product'])


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0011_add_product_to_knowledge_models"),
        ("products", "0015_add_default_language"),
    ]

    operations = [
        migrations.RunPython(
            backfill_product_on_sources,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_product_on_items,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_product_on_chunks,
            migrations.RunPython.noop,
        ),
    ]
