# Generated by Django 5.2.9 on 2026-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0012_backfill_product_from_org_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("page", "Web Page"),
                    ("snippet", "Snippet"),
                    ("correction", "Correction"),
                ],
                db_index=True,
                help_text="Type of content item",
                max_length=20,
            ),
        ),
    ]
