# Generated by Django 5.2.9 on 2026-02-09 21:31

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0013_add_correction_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correction",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgechunk",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeitem",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgesynchistory",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="pendingupload",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
