# Generated by Django 5.2.9 on 2026-02-12 02:36

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0014_alter_correction_id_alter_knowledgechunk_id_and_more"),
        ("products", "0018_alter_action_id_alter_actiondeployment_id_and_more"),
        ("users", "0005_alter_organization_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="kchunk_embedding_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
