# Generated by Django 5.2.9 on 2026-02-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0015_knowledgechunk_kchunk_embedding_hnsw_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesynchistory",
            name="items_deleted",
            field=models.IntegerField(
                default=0, help_text="Stale items removed (no longer found at source)"
            ),
        ),
    ]
