# Generated by Django 5.2.9 on 2026-03-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0016_knowledgesynchistory_items_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgechunk",
            name="title",
            field=models.TextField(help_text="Chunk title (usually the heading)"),
        ),
    ]
