# Generated by Django 5.2.9 on 2026-03-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0017_chunk_title_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesource",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("external", "External"),
                    ("all", "All"),
                ],
                db_index=True,
                default="all",
                help_text="Visibility tag for agent knowledge scoping",
                max_length=20,
            ),
        ),
    ]
