# Generated by Django 5.2.9 on 2026-03-18 23:12

import django.db.models.deletion
import encrypted_fields.fields
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0026_add_agent_to_conversation"),
        ("products", "0032_migrate_web_agents"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild_id",
                    models.CharField(
                        db_index=True,
                        help_text="Discord guild (server) snowflake ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "guild_name",
                    models.CharField(
                        help_text="Human-readable guild name", max_length=255
                    ),
                ),
                (
                    "bot_token",
                    encrypted_fields.fields.EncryptedTextField(
                        help_text="Bot token from Discord OAuth. Encrypted at rest via Fernet."
                    ),
                ),
                (
                    "bot_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Bot user snowflake ID in this guild",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False if removed from guild or deactivated from dashboard",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Channel restrictions, DM settings, etc.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this Discord server is connected to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_installations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Installation",
                "verbose_name_plural": "Discord Installations",
            },
        ),
        migrations.CreateModel(
            name="DiscordConversationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guild_id",
                    models.CharField(
                        db_index=True,
                        help_text="Discord guild snowflake (denormalised for query convenience)",
                        max_length=50,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        db_index=True,
                        help_text="Discord channel snowflake",
                        max_length=50,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Discord thread snowflake (empty for DMs)",
                        max_length=50,
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_mapping",
                        to="analytics.chatconversation",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_mappings",
                        to="discord_integration.discordinstallation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Conversation Mapping",
                "verbose_name_plural": "Discord Conversation Mappings",
            },
        ),
        migrations.AddIndex(
            model_name="discordinstallation",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="idx_discord_inst_org_created",
            ),
        ),
        migrations.AddIndex(
            model_name="discordinstallation",
            index=models.Index(
                fields=["product", "is_active"], name="idx_discord_inst_prod_active"
            ),
        ),
        migrations.AddIndex(
            model_name="discordconversationmapping",
            index=models.Index(
                fields=["installation", "channel_id", "thread_id"],
                name="idx_discord_conv_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordconversationmapping",
            constraint=models.UniqueConstraint(
                fields=("installation", "channel_id", "thread_id"),
                name="uq_discord_conv_mapping",
            ),
        ),
    ]
