# Generated by Django 5.2.9 on 2026-03-19 23:05

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_integration', '0001_initial'),
        ('products', '0034_agent_knowledge_scope_agent_knowledge_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordinstallation',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Specific agent to route messages to. Null = use product+channel resolver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_installations', to='products.agent'),
        ),
        migrations.AddField(
            model_name='discordinstallation',
            name='app_public_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, default='', help_text='Per-installation public key for Ed25519 interaction verification.', null=True),
        ),
        migrations.AddField(
            model_name='discordinstallation',
            name='is_byob',
            field=models.BooleanField(default=False, help_text='True if customer provided their own Discord bot credentials.'),
        ),
    ]
