# Generated by Django 5.2.9 on 2026-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_integration', '0002_discordinstallation_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordinstallation',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Discord application snowflake ID. Used to route incoming interactions.', max_length=50),
        ),
    ]
