# Generated by Django 5.2.9 on 2025-12-18 21:23

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorEmbedding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of content: 'article', 'tutorial', 'category', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the content item"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="The text that was embedded"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        db_column="metadata_",
                        default=dict,
                        help_text="Additional metadata (heading hierarchy, chunk info, etc.)",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        blank=True,
                        help_text="LlamaIndex node ID for tracking",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536,
                        help_text="Vector embedding from embedding model",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Name of the embedding model used",
                        max_length=100,
                    ),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider: 'openai', 'google', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        blank=True,
                        help_text="Version string for cache invalidation",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_embeddings",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "db_table": "help_center_vector_embeddings",
                "indexes": [
                    models.Index(
                        fields=["organization", "content_type", "content_id"],
                        name="hc_embed_org_content_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="hc_embed_content_idx",
                    ),
                    models.Index(
                        fields=["embedding_version"], name="hc_embed_version_idx"
                    ),
                ],
            },
        ),
    ]
