# Generated by Django 5.2.9 on 2025-12-19 20:34

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("article", "Help Article"),
                            ("tutorial", "Tutorial"),
                            ("internal_page", "Internal Page"),
                            ("internal_kms", "Internal KMS Page"),
                            ("internal_ticket", "Internal Ticket"),
                        ],
                        db_index=True,
                        help_text="Type of content this chunk was extracted from",
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the source content (article, tutorial, etc.)",
                    ),
                ),
                (
                    "source_heading",
                    models.CharField(
                        blank=True,
                        help_text="H2/H3 heading this chunk came from",
                        max_length=500,
                    ),
                ),
                (
                    "source_heading_hierarchy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Full heading hierarchy: ['H1 Title', 'H2 Section', 'H3 Subsection']",
                        size=None,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of this chunk (usually the heading)",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual text content of this chunk"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary (optional, for display in search results)",
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("procedure", "Step-by-step procedure"),
                            ("concept", "Explanation or definition"),
                            ("prerequisite", "Requirement or prerequisite"),
                            ("warning", "Caution or limitation"),
                            ("faq", "Question and answer"),
                            ("reference", "Reference information (tables, specs)"),
                            ("overview", "Introduction or overview"),
                            ("example", "Example or use case"),
                        ],
                        db_index=True,
                        default="concept",
                        help_text="Semantic type of this chunk",
                        max_length=20,
                    ),
                ),
                (
                    "topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Extracted topic tags for filtering",
                        size=None,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding for semantic search",
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Model used to generate embedding",
                        max_length=100,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="MD5 hash of source content for staleness detection",
                        max_length=32,
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if source content has changed since extraction",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this chunk was extracted"
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When embedding was last generated",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Chunk",
                "verbose_name_plural": "Knowledge Chunks",
                "db_table": "common_knowledgechunk",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraphEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("article", "Article"), ("chunk", "Knowledge Chunk")],
                        help_text="Type of the source node",
                        max_length=10,
                    ),
                ),
                (
                    "source_article_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of source article (if source_type='article')",
                        null=True,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("article", "Article"), ("chunk", "Knowledge Chunk")],
                        help_text="Type of the target node",
                        max_length=10,
                    ),
                ),
                (
                    "target_article_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of target article (if target_type='article')",
                        null=True,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        db_index=True,
                        help_text="Relationship type: 'prerequisite_for', 'explains', 'next_step', 'contains', etc.",
                        max_length=200,
                    ),
                ),
                (
                    "inverse_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Inverse relationship: 'requires', 'is_explained_by', 'previous_step', etc.",
                        max_length=200,
                    ),
                ),
                (
                    "is_symmetric",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this relationship is bidirectional (e.g., 'related_to')",
                    ),
                ),
                (
                    "fact_statement",
                    models.TextField(
                        help_text="Natural language description of this relationship"
                    ),
                ),
                (
                    "fact_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Embedding of fact_statement for semantic deduplication",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("extraction", "Chunk Extraction"),
                            ("librarian", "Librarian Agent"),
                            ("human", "Human"),
                            ("import", "Imported"),
                        ],
                        default="extraction",
                        help_text="What created this edge",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence score (0.0-1.0) for AI-generated edges",
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of why this relationship was identified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of this edge",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this edge was reviewed", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this edge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_knowledge_edges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source chunk (if source_type='chunk')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="common.knowledgechunk",
                    ),
                ),
                (
                    "target_chunk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target chunk (if target_type='chunk')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="common.knowledgechunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Graph Edge",
                "verbose_name_plural": "Knowledge Graph Edges",
                "db_table": "common_knowledgegraphedge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["organization", "source_type", "source_id"],
                name="common_know_organiz_1cd486_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["organization", "chunk_type"],
                name="common_know_organiz_c3f66e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["organization", "is_stale"],
                name="common_know_organiz_626fe1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["source_id", "content_hash"],
                name="common_know_source__05a6dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_type", "source_id", "content_hash"),
                name="unique_chunk_per_source_content",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["organization", "status"], name="common_know_organiz_97f7b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["organization", "relationship"],
                name="common_know_organiz_7d8ed2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["source_type", "source_article_id"],
                name="common_know_source__f3eee7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["source_type", "source_chunk"],
                name="common_know_source__2c5b1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["target_type", "target_article_id"],
                name="common_know_target__7ddd0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["target_type", "target_chunk"],
                name="common_know_target__91cc69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgegraphedge",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="common_know_created_060dfc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgegraphedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_article_id__isnull", False),
                        ("source_chunk__isnull", True),
                        ("source_type", "article"),
                    ),
                    models.Q(
                        ("source_article_id__isnull", True),
                        ("source_chunk__isnull", False),
                        ("source_type", "chunk"),
                    ),
                    _connector="OR",
                ),
                name="valid_source_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgegraphedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_article_id__isnull", False),
                        ("target_chunk__isnull", True),
                        ("target_type", "article"),
                    ),
                    models.Q(
                        ("target_article_id__isnull", True),
                        ("target_chunk__isnull", False),
                        ("target_type", "chunk"),
                    ),
                    _connector="OR",
                ),
                name="valid_target_node",
            ),
        ),
    ]
