# Generated by Django 5.2.9 on 2026-01-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_migrate_article_relationships'),
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='knowledgegraphedge',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization'),
        ),
    ]
