# Generated by Django 5.2.9 on 2026-01-20 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_update_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the waitlist signup",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person signing up",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Company name", max_length=255
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        blank=True,
                        help_text="What they're hoping to accomplish with Pillar",
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="UTM source or referral tracking",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address at signup time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invited", "Invited"),
                            ("converted", "Converted to User"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the waitlist entry",
                        max_length=50,
                    ),
                ),
                (
                    "queue_position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the waitlist queue"
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="waitlist_email_idx"),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="waitlist_status_created_idx",
                    ),
                ],
            },
        ),
    ]
