# Generated by Django 5.2.9 on 2026-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_waitlistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="heard_about_us",
            field=models.CharField(
                blank=True,
                help_text="How the user heard about Pillar (from predefined list or custom)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="heard_about_us_other",
            field=models.CharField(
                blank=True,
                help_text="Custom text if heard_about_us is 'other'",
                max_length=255,
            ),
        ),
    ]
