# Generated by Django 5.2.9 on 2026-02-09 21:31

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_add_heard_about_us_to_waitlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgechunk",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgegraphedge",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="id",
            field=models.UUIDField(
                default=uuid_utils._uuid_utils.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
