"""
Centralized agent messages with LLM generation capability.

Replaces scattered hardcoded fallback messages with contextual,
LLM-generated messages that fall back to templates on failure.

Copyright (C) 2025 Pillar Team
"""
import logging
from typing import List, Optional

logger = logging.getLogger(__name__)


class AgentMessages:
    """
    Centralized agent messages with LLM generation capability.
    
    Provides contextual messages that are generated by the LLM when possible,
    with safe template fallbacks when LLM calls fail.
    """
    
    @staticmethod
    async def get_no_results_message(
        llm_client,
        question: str,
        product_name: str,
        searched_types: Optional[List[str]] = None,
        timeout: float = 5.0,
    ) -> str:
        """
        Generate a contextual 'no results' message.
        
        Instead of hardcoded "I couldn't find...", ask the LLM to 
        craft an appropriate response based on what was searched.
        Falls back to template on LLM failure.
        
        Args:
            llm_client: The LLM client instance
            question: The user's original question
            product_name: Name of the product/help center
            searched_types: List of what was searched (e.g., ["actions", "knowledge"])
            timeout: Maximum time to wait for LLM response
            
        Returns:
            Contextual message string
        """
        import asyncio
        
        searched_types = searched_types or ["documentation"]
        searched_str = ", ".join(searched_types)
        
        # First, try a quick LLM call to generate contextual response
        try:
            prompt = f"""The user asked: "{question}"
We searched {searched_str} but found nothing relevant.
Write a brief, helpful response (1-2 sentences) that:
- Acknowledges we couldn't find specific info
- Suggests an alternative (rephrase, contact support, etc.)
Keep it natural and concise. Don't use phrases like "I apologize" or "I'm sorry"."""
            
            response = await asyncio.wait_for(
                llm_client.complete_async(
                    prompt=prompt,
                    system_prompt=f"You are a helpful assistant for {product_name}. Be concise and helpful.",
                    max_tokens=100,
                    temperature=0.3,
                ),
                timeout=timeout,
            )
            
            if response and response.strip():
                logger.debug(f"[AgentMessages] Generated no-results message via LLM")
                return response.strip()
                
        except asyncio.TimeoutError:
            logger.debug(f"[AgentMessages] LLM timed out for no-results message")
        except Exception as e:
            logger.debug(f"[AgentMessages] LLM failed for no-results message: {e}")
        
        # Fallback to template-based message
        return f"I searched our {searched_str} but couldn't find specific information about that. Could you try rephrasing your question, or would you like to contact our support team?"
    
    @staticmethod
    async def get_error_recovery_message(
        llm_client,
        question: str,
        product_name: str,
        error_context: str = "processing your request",
        timeout: float = 5.0,
    ) -> str:
        """
        Generate a message when recovering from an error.
        
        Used when the agent encounters an error but can still respond.
        
        Args:
            llm_client: The LLM client instance
            question: The user's original question
            product_name: Name of the product/help center
            error_context: Brief description of what failed
            timeout: Maximum time to wait for LLM response
            
        Returns:
            Recovery message string
        """
        import asyncio
        
        try:
            prompt = f"""We had trouble {error_context} for the user's question: "{question}"
Write a brief, helpful response (1-2 sentences) that:
- Doesn't mention technical errors or apologize excessively
- Offers to help in a different way or suggests they rephrase
Keep it natural and constructive."""
            
            response = await asyncio.wait_for(
                llm_client.complete_async(
                    prompt=prompt,
                    system_prompt=f"You are a helpful assistant for {product_name}. Be concise.",
                    max_tokens=80,
                    temperature=0.3,
                ),
                timeout=timeout,
            )
            
            if response and response.strip():
                logger.debug(f"[AgentMessages] Generated error recovery message via LLM")
                return response.strip()
                
        except Exception as e:
            logger.debug(f"[AgentMessages] LLM failed for error recovery message: {e}")
        
        # Fallback template
        return "I'm having trouble with that request. Could you try rephrasing your question?"
    
    @staticmethod
    def get_fallback_message() -> str:
        """
        Return the standard fallback message.
        
        This is the simple template fallback when no LLM is available
        or when we need an immediate response.
        
        Returns:
            Static fallback message string
        """
        return (
            "I couldn't find specific information about that in our documentation. "
            "Would you like me to help you with something else, or would you prefer "
            "to contact our support team for more detailed assistance?"
        )
    
    @staticmethod
    def get_injection_response() -> str:
        """
        Return a safe response for detected injection attempts.
        
        Returns:
            Static injection response string
        """
        return (
            "I'm here to help answer questions about our products and services. "
            "Could you please rephrase your question?"
        )
    
    @staticmethod
    def get_defer_message_with_action() -> str:
        """
        Return message for defer when a support action is available.
        
        Returns:
            Static defer message string
        """
        return (
            "I wasn't able to find specific information about that. "
            "Would you like to talk to our support team?"
        )
    
    @staticmethod
    def get_escalate_message() -> str:
        """
        Return message for user-requested escalation to human support.
        
        Returns:
            Static escalation message string
        """
        return "I'll connect you with our support team right away."
    
    @staticmethod
    def get_escalate_message_no_action() -> str:
        """
        Return message when escalation requested but no support action configured.
        
        Returns:
            Static no-action escalation message string
        """
        return (
            "I'd like to connect you with our support team, but I don't have "
            "a direct way to do that. Please contact support through your usual channels."
        )


# Convenience functions that wrap the class methods for backward compatibility
async def get_contextual_no_results_message(
    llm_client,
    question: str,
    product_name: str,
    searched_types: Optional[List[str]] = None,
) -> str:
    """
    Convenience function for getting a contextual no-results message.
    
    See AgentMessages.get_no_results_message for details.
    """
    return await AgentMessages.get_no_results_message(
        llm_client=llm_client,
        question=question,
        product_name=product_name,
        searched_types=searched_types,
    )


def get_fallback_message() -> str:
    """
    Return the standard fallback message.
    
    This is a drop-in replacement for the old helpers.get_fallback_message().
    """
    return AgentMessages.get_fallback_message()


def get_injection_response() -> str:
    """
    Return a safe response for detected injection attempts.
    
    This is a drop-in replacement for the old helpers.get_injection_response().
    """
    return AgentMessages.get_injection_response()


def get_defer_message_with_action() -> str:
    """
    Return message for defer when a support action is available.
    
    This is a drop-in replacement for the old helpers.get_defer_message_with_action().
    """
    return AgentMessages.get_defer_message_with_action()


def get_escalate_message() -> str:
    """
    Return message for user-requested escalation.
    
    This is a drop-in replacement for the old helpers.get_escalate_message().
    """
    return AgentMessages.get_escalate_message()


def get_escalate_message_no_action() -> str:
    """
    Return message when escalation requested but no action available.
    
    This is a drop-in replacement for the old helpers.get_escalate_message_no_action().
    """
    return AgentMessages.get_escalate_message_no_action()
