# Generated by Django 5.2.9 on 2026-01-12 22:50

import apps.products.models.product
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_add_billing_email_and_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_type', models.CharField(choices=[('desktop_web', 'Desktop Web'), ('mobile_web', 'Mobile Web'), ('ios_app', 'iOS App'), ('android_app', 'Android App'), ('desktop_app', 'Desktop App')], help_text='Type of platform', max_length=20)),
                ('name', models.CharField(help_text="Display name (e.g., 'Desktop Web', 'Mobile App')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this platform active?')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Platform-specific configuration (viewport, user_agent, etc.)')),
                ('scrape_cadence_hours', models.PositiveIntegerField(blank=True, help_text='How often to scrape this platform (hours). Null uses source default.', null=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['platform_type'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Product', help_text="Display name for this product (e.g., 'Customer Support', 'Internal Docs')", max_length=100)),
                ('subdomain', models.CharField(db_index=True, help_text="Unique subdomain for this product (e.g., 'acme' for acme.help.pillar.io)", max_length=50, unique=True, validators=[apps.products.models.product.validate_subdomain])),
                ('website_url', models.URLField(blank=True, default='', help_text='Primary website URL for the product', max_length=500)),
                ('config', models.JSONField(default=dict, help_text='Product configuration (branding, layout, features, etc.)')),
                ('is_default', models.BooleanField(default=True, help_text='Whether this is the default product for the organization')),
                ('auto_theme_generated', models.BooleanField(default=False, help_text='Whether theme was auto-generated from brand analysis')),
                ('show_article_owner', models.BooleanField(default=False, help_text='Show article owner on public article pages (can be overridden per-article)')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name for this tooltip (e.g., 'Garnishment type selector')", max_length=100)),
                ('tooltip_id', models.SlugField(help_text="Developer-facing ID used in data-pillar-tooltip attribute (e.g., 'garnishment-type-select')", max_length=100)),
                ('content', models.TextField(help_text='Tooltip content in markdown (recommended max ~200 chars)')),
                ('content_html', models.TextField(blank=True, default='', help_text='Pre-rendered HTML content')),
                ('show_learn_more', models.BooleanField(default=True, help_text="Show 'Learn more' link to linked article")),
                ('trigger', models.CharField(choices=[('hover', 'Hover'), ('click', 'Click'), ('focus', 'Focus'), ('icon', 'Icon')], default='hover', help_text='How the tooltip is triggered', max_length=10)),
                ('position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('auto', 'Auto')], default='auto', help_text='Preferred position of the tooltip', max_length=10)),
                ('status', models.CharField(choices=[('ai_suggested', 'AI Suggested'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When this tooltip was published', null=True)),
                ('ai_generated', models.BooleanField(db_index=True, default=False, help_text='Whether this tooltip was generated by AI')),
                ('ai_suggested_placement', models.TextField(blank=True, default='', help_text="AI's suggestion for where to place this tooltip in the UI")),
            ],
            options={
                'verbose_name': 'Tooltip',
                'verbose_name_plural': 'Tooltips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Unique action identifier (e.g., 'open_invite_flow'). Used by SDK to identify the action and derive button label.", max_length=100)),
                ('description', models.TextField(help_text='Description for AI to understand when to suggest this action. Be specific about use cases. Used for semantic matching.')),
                ('description_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Embedding vector for semantic matching against user queries', null=True)),
                ('action_type', models.CharField(choices=[('navigate', 'Navigate to Page'), ('open_modal', 'Open Modal/Dialog'), ('fill_form', 'Fill Form Fields'), ('trigger_action', 'Trigger Custom Action'), ('copy_text', 'Copy to Clipboard'), ('external_link', 'Open External Link'), ('start_tutorial', 'Start Tutorial/Walkthrough'), ('inline_ui', 'Inline UI Card')], default='trigger_action', help_text='Type of action this action performs', max_length=50)),
                ('path_template', models.CharField(blank=True, help_text='URL path template with {param} placeholders. Example: /settings/team?action={action}', max_length=500)),
                ('external_url', models.URLField(blank=True, help_text='External URL to open', max_length=2000)),
                ('data_schema', models.JSONField(blank=True, default=dict, help_text="JSON Schema defining the action's data payload")),
                ('default_data', models.JSONField(blank=True, default=dict, help_text='Default values for data payload')),
                ('required_context', models.JSONField(blank=True, default=dict, help_text="Required context values (e.g., {'userRole': 'admin'})")),
                ('auto_run', models.BooleanField(default=False, help_text='If True, action executes immediately when suggested by AI without requiring user to click a button. Use for safe, reversible actions like navigation.')),
                ('auto_complete', models.BooleanField(default=False, help_text='If True, action completes immediately after execution without waiting for host app confirmation. Use for simple navigations and clipboard operations.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('execution_count', models.PositiveIntegerField(default=0, help_text='Number of times this action was executed')),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='When this action was last executed', null=True)),
                ('implementation_status', models.CharField(choices=[('unknown', 'Unknown'), ('verified', 'Verified Working'), ('failing', 'Failing'), ('stale', 'Stale (no recent confirmations)')], db_index=True, default='unknown', help_text='Whether the client implementation is verified working', max_length=20)),
                ('confirmation_success_count', models.PositiveIntegerField(default=0, help_text='Number of successful execution confirmations')),
                ('confirmation_failure_count', models.PositiveIntegerField(default=0, help_text='Number of failed execution confirmations')),
                ('last_confirmed_at', models.DateTimeField(blank=True, help_text='When we last received an execution confirmation', null=True)),
                ('last_confirmation_status', models.CharField(blank=True, help_text="Status of last confirmation: 'success' or 'failure'", max_length=20)),
                ('last_confirmation_error', models.TextField(blank=True, help_text='Error message from last failed confirmation')),
                ('organization', models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, help_text='Widget session ID', max_length=100)),
                ('conversation_id', models.UUIDField(blank=True, help_text='Conversation where action was suggested', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], help_text='Execution result status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional execution metadata from SDK')),
                ('action', models.ForeignKey(help_text='The action that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='products.action')),
                ('organization', models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'verbose_name': 'Action Execution Log',
                'verbose_name_plural': 'Action Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
