# Generated by Django 5.2.9 on 2026-01-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('content', '0003_initial'),  # Removed - content app deleted
        ('products', '0001_initial'),
        # ('sources', '0001_initial'),  # Removed - sources app deleted
        ('users', '0002_add_billing_email_and_onboarding_step'),
        ('knowledge', '0001_initial'),  # Added for KnowledgeItem FK
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='product',
            field=models.ForeignKey(help_text='Product this platform belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='products.product', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(help_text='Organization this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.organization'),
        ),
        migrations.AddField(
            model_name='action',
            name='product',
            field=models.ForeignKey(help_text='Product this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='products.product'),
        ),
        migrations.AddField(
            model_name='tooltip',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, help_text="Optional linked knowledge item for 'Learn more' link", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooltips', to='knowledge.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='tooltip',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this data', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization'),
        ),
        migrations.AddField(
            model_name='tooltip',
            name='product',
            field=models.ForeignKey(help_text='Product this tooltip belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='actionexecutionlog',
            index=models.Index(fields=['action', '-created_at'], name='products_ac_action__aee84e_idx'),
        ),
        migrations.AddIndex(
            model_name='actionexecutionlog',
            index=models.Index(fields=['organization', '-created_at'], name='products_ac_organiz_76fc79_idx'),
        ),
        migrations.AddIndex(
            model_name='actionexecutionlog',
            index=models.Index(fields=['status', '-created_at'], name='products_ac_status_4f6f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['product', 'is_active'], name='products_pl_product_aca5fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('product', 'platform_type')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_default'], name='products_pr_organiz_641fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['organization', 'status'], name='products_ac_organiz_3f1c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['product', 'status'], name='products_ac_product_e73aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['organization', 'name'], name='products_ac_organiz_fa5e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['organization', 'implementation_status'], name='products_ac_organiz_7ccbc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='tooltip',
            index=models.Index(fields=['product', 'status'], name='products_to_product_59637e_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltip',
            index=models.Index(fields=['product', '-created_at'], name='products_to_product_8b8acd_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltip',
            index=models.Index(fields=['knowledge_item', 'status'], name='products_to_knowled_af5364_idx'),
        ),
        migrations.AddIndex(
            model_name='tooltip',
            index=models.Index(fields=['organization', 'status'], name='products_to_organiz_dedb1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tooltip',
            unique_together={('product', 'tooltip_id')},
        ),
    ]
