# Generated by Django 5.2.9 on 2026-01-13 04:01

import common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="actions_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable code-first action sync from client deployments",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="actions_sync_secret",
            field=common.fields.EncryptedTextField(
                blank=True,
                null=True,
                default='',
                help_text="Secret token for authenticating action sync requests from CI/CD (encrypted at rest)",
            ),
        ),
        migrations.CreateModel(
            name="ActionDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("desktop", "Desktop"),
                        ],
                        db_index=True,
                        help_text="Platform this deployment is for (web, ios, android, desktop)",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        db_index=True,
                        help_text="Semantic version or git SHA (e.g., '1.2.3' or 'abc123')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this deployment is accepting requests",
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this deployment was created"
                    ),
                ),
                (
                    "deployed_by",
                    models.CharField(
                        blank=True,
                        help_text="CI/CD pipeline or user that created this deployment",
                        max_length=100,
                    ),
                ),
                (
                    "git_sha",
                    models.CharField(
                        blank=True,
                        help_text="Git commit SHA for this deployment",
                        max_length=40,
                    ),
                ),
                (
                    "manifest_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA256 hash of the action manifest for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "actions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Actions available in this deployment",
                        related_name="deployments",
                        to="products.action",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this deployment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_deployments",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Deployment",
                "verbose_name_plural": "Action Deployments",
                "ordering": ["-deployed_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "platform", "is_active"],
                        name="products_ac_product_4268d3_idx",
                    ),
                    models.Index(
                        fields=["organization", "platform", "is_active"],
                        name="products_ac_organiz_a2b04a_idx",
                    ),
                ],
                "unique_together": {("product", "platform", "version")},
            },
        ),
    ]
