# Generated by Django 5.2.9 on 2026-01-13 05:18
# Modified: Use conditional SQL to handle both fresh and existing databases
#
# For existing databases:
#   - Platform.product was renamed from data_source - DB might have old index name
#   - Tooltip.knowledge_item was renamed from article - DB might have old index name
#
# For fresh databases (CI):
#   - Indexes created correctly in earlier migrations, no rename needed

from django.db import migrations


def rename_indexes_if_needed(apps, schema_editor):
    """Rename old index names to new names only if old names exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check and rename Platform index (data_source -> product)
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'products_pl_data_so_aca5fb_idx'
            )
        """)
        old_platform_index_exists = cursor.fetchone()[0]
        
        if old_platform_index_exists:
            cursor.execute("""
                ALTER INDEX "products_pl_data_so_aca5fb_idx" 
                RENAME TO "products_pl_product_aca5fb_idx"
            """)
        
        # Check and rename Tooltip index (article -> knowledge_item)
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'products_to_article_af5364_idx'
            )
        """)
        old_tooltip_index_exists = cursor.fetchone()[0]
        
        if old_tooltip_index_exists:
            cursor.execute("""
                ALTER INDEX "products_to_article_af5364_idx" 
                RENAME TO "products_to_knowled_af5364_idx"
            """)


def noop(apps, schema_editor):
    """Reverse operation - no-op since we can't know the original state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_actions_sync_enabled_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_needed, noop),
    ]
