# Generated by Django 5.2.9 on 2026-01-13 18:39
# Modified: Use conditional SQL to handle cases where indexes don't exist

from django.db import migrations, models


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check and rename Platform index
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'products_pl_product_aca5fb_idx'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                ALTER INDEX "products_pl_product_aca5fb_idx" 
                RENAME TO "products_pl_product_00089a_idx"
            """)
        
        # Check and rename Tooltip index
        cursor.execute("""
            SELECT EXISTS(
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'products_to_knowled_af5364_idx'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute("""
                ALTER INDEX "products_to_knowled_af5364_idx" 
                RENAME TO "products_to_knowled_f6b5be_idx"
            """)


def noop(apps, schema_editor):
    """Reverse operation - no-op since we can't know the original state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_rename_products_pl_product_aca5fb_idx_products_pl_product_00089a_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, noop),
        migrations.AddField(
            model_name="action",
            name="example_embeddings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Embedding vectors for each example (list of 1536-dim vectors)",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="examples",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Example user queries that trigger this action (e.g., 'open settings', 'go to billing')",
            ),
        ),
    ]
