# Generated by Django 5.2.9 on 2026-01-13 22:34

import apps.products.models.sync_secret
import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_action_sync_job"),
        ("users", "0002_add_billing_email_and_onboarding_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this secret (e.g., 'production', 'staging')",
                        max_length=50,
                        validators=[
                            apps.products.models.sync_secret.validate_secret_name
                        ],
                    ),
                ),
                (
                    "secret_hash",
                    common.fields.EncryptedTextField(
                        help_text="The sync secret (encrypted at rest)"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last time this secret was used for a sync",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Secret",
                "verbose_name_plural": "Sync Secrets",
            },
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this secret",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sync_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that owns this data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="product",
            field=models.ForeignKey(
                help_text="Product this secret belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_secrets",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="syncsecret",
            index=models.Index(
                fields=["product", "-created_at"], name="products_sy_product_1197b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncsecret",
            unique_together={("product", "name")},
        ),
    ]
