# Generated by Django 5.2.9 on 2026-01-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_sync_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="actions_sync_enabled",
        ),
        migrations.RemoveField(
            model_name="product",
            name="actions_sync_secret",
        ),
    ]
