# Generated by Django 5.2.9 on 2026-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_legacy_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="returns_data",
            field=models.BooleanField(
                default=False,
                help_text="If True, action returns data for the agent to use in further reasoning. Handler must return a JSON-serializable object. Use for query/lookup actions.",
            ),
        ),
    ]
