# Generated by Django 5.2.9 on 2026-01-15 01:05
# Modified: Use SeparateDatabaseAndState to properly track index renames

from django.db import migrations, models


# Index rename mappings: (model_name, old_name, new_name, fields)
INDEX_RENAMES = [
    ("actionsyncjob", "products_ac_product_status_idx", "products_ac_product_69b6f9_idx", ["product", "status"]),
    ("actionsyncjob", "products_ac_product_platform_version_idx", "products_ac_product_29becf_idx", ["product", "platform", "version"]),
    ("actionsyncjob", "products_ac_manifest_hash_idx", "products_ac_manifes_abfb83_idx", ["manifest_hash"]),
    ("actionsyncjob", "products_ac_organization_status_idx", "products_ac_organiz_6c5fe5_idx", ["organization", "status"]),
    ("actionsyncjob", "products_ac_is_complete_idx", "products_ac_is_comp_8b2ce9_idx", ["is_complete"]),
    ("platform", "products_pl_product_aca5fb_idx", "products_pl_product_00089a_idx", ["product", "is_active"]),
    # Note: Tooltip index NOT renamed - keeping products_to_knowled_af5364_idx
]


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        for model_name, old_name, new_name, fields in INDEX_RENAMES:
            cursor.execute(
                """
                SELECT EXISTS(
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
                """,
                [old_name],
            )
            if cursor.fetchone()[0]:
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
                )


def noop(apps, schema_editor):
    """Reverse operation - no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_add_returns_data_to_action"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_if_exist, noop),
            ],
            state_operations=[
                # ActionSyncJob index renames
                migrations.RenameIndex(
                    model_name="actionsyncjob",
                    old_name="products_ac_product_status_idx",
                    new_name="products_ac_product_69b6f9_idx",
                ),
                migrations.RenameIndex(
                    model_name="actionsyncjob",
                    old_name="products_ac_product_platform_version_idx",
                    new_name="products_ac_product_29becf_idx",
                ),
                migrations.RenameIndex(
                    model_name="actionsyncjob",
                    old_name="products_ac_manifest_hash_idx",
                    new_name="products_ac_manifes_abfb83_idx",
                ),
                migrations.RenameIndex(
                    model_name="actionsyncjob",
                    old_name="products_ac_organization_status_idx",
                    new_name="products_ac_organiz_6c5fe5_idx",
                ),
                migrations.RenameIndex(
                    model_name="actionsyncjob",
                    old_name="products_ac_is_complete_idx",
                    new_name="products_ac_is_comp_8b2ce9_idx",
                ),
                # Platform index rename
                migrations.RenameIndex(
                    model_name="platform",
                    old_name="products_pl_product_aca5fb_idx",
                    new_name="products_pl_product_00089a_idx",
                ),
            ],
        ),
    ]
