# Generated by Django 5.2.9 on 2026-01-15 23:27
# Modified: Use SeparateDatabaseAndState since column already exists with correct name

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0008_correction_reasoning_fields"),
        (
            "products",
            "0010_rename_products_ac_product_status_idx_products_ac_product_69b6f9_idx_and_more",
        ),
    ]

    operations = [
        # Use SeparateDatabaseAndState because the column already exists as 'article_id'
        # We just need to update Django's state to know about db_column
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="tooltip",
                    name="knowledge_item",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="article_id",
                        help_text="Optional linked knowledge item for 'Learn more' link",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tooltips",
                        to="knowledge.knowledgeitem",
                    ),
                ),
            ],
            database_operations=[
                # No database operations needed - column already exists with correct name
            ],
        ),
    ]
