# Generated by Django 5.2.9 on 2026-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_drop_tooltip_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sdk_last_initialized_at',
            field=models.DateTimeField(blank=True, help_text='When the SDK last called the embed-config endpoint', null=True),
        ),
    ]
