# Generated by Django 5.2.9 on 2026-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_add_query_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_language",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect from browser"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                    ("it", "Italian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                ],
                default="auto",
                help_text="Default language for AI responses. 'auto' detects from user's browser.",
                max_length=10,
            ),
        ),
    ]
