# Generated by Django 5.2.9 on 2026-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_add_default_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="agent_guidance",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom instructions for the AI agent. Injected into the agent prompt for product-specific guidance.",
            ),
        ),
    ]
