# Generated by Django 5.2.9 on 2026-02-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_add_agent_guidance"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="parameter_examples",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Examples of valid parameter objects for the LLM to reference. Each example should have 'description' and 'parameters' fields.",
            ),
        ),
    ]
