# Generated by Django 5.2.9 on 2026-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_drop_orphaned_action_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='guidance',
            field=models.TextField(blank=True, default='', help_text="Agent-facing instructions for when/how to use this tool. Appended to the tool description in the LLM's tool list. Use for disambiguation and prerequisite hints."),
        ),
    ]
