# Generated by Django 5.2.9 on 2026-02-20 00:46

import apps.products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_add_guidance_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subdomain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique subdomain for this product (e.g., 'acme' for acme.help.pillar.io)",
                max_length=50,
                null=True,
                unique=True,
                validators=[apps.products.models.product.validate_subdomain],
            ),
        ),
    ]
