# Generated by Django 5.2.9 on 2026-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_allow_null_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="output_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON Schema describing output. Properties with 'sensitive': true are stripped from AI context and delivered via the secure redemption flow.",
            ),
        ),
    ]
