# Generated by Django 5.2.9 on 2026-03-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_add_output_schema_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Product configuration (branding, layout, features, etc.)",
            ),
        ),
    ]
