# Generated by Django 5.2.9 on 2026-03-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_alter_product_config"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("product", "name")},
        ),
    ]
