# Generated by Django 5.2.9 on 2026-03-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_alter_action_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="channel_compatibility",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of channels where this tool is available. Default: ['web'] for client-side, all channels for server-side.",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("client_side", "Client-Side"),
                    ("server_side", "Server-Side"),
                ],
                db_index=True,
                default="client_side",
                help_text="Whether this tool runs in the user's browser (client-side) or on the customer's server (server-side)",
                max_length=20,
            ),
        ),
    ]
