# Generated by Django 5.2.9 on 2026-03-17 20:32

from django.db import migrations


def backfill_channel_compatibility(apps, schema_editor):
    Action = apps.get_model('products', 'Action')
    Action.objects.filter(channel_compatibility=[]).update(
        channel_compatibility=['web']
    )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_add_tool_type_and_channel_compatibility"),
    ]

    operations = [
        migrations.RunPython(backfill_channel_compatibility, migrations.RunPython.noop),
    ]
