# Generated by Django 5.2.9 on 2026-03-17 22:34

import common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_backfill_channel_compatibility"),
        ("users", "0008_add_usage_alert_last_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="syncsecret",
            new_name="syncsecret_product_created_idx",
            old_name="products_sy_product_1197b2_idx",
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this secret can be used for authentication",
            ),
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="last_four",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last 4 characters of the secret for dashboard display",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="syncsecret",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, help_text="When this secret was revoked", null=True
            ),
        ),
        migrations.AlterField(
            model_name="syncsecret",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time this secret was used",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncsecret",
            name="secret_hash",
            field=common.fields.EncryptedTextField(
                help_text="The secret value (encrypted at rest via Fernet)"
            ),
        ),
        migrations.AddIndex(
            model_name="syncsecret",
            index=models.Index(
                fields=["product", "is_active"], name="syncsecret_product_active_idx"
            ),
        ),
    ]
