# Generated by Django 5.2.9 on 2026-03-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_add_sync_secret_rotation_fields"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="mcp_source",
            field=models.ForeignKey(
                blank=True,
                help_text="MCP source this tool was discovered from (if source_type='mcp')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tools",
                to="tools.mcptoolsource",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("cli_sync", "CLI Sync"),
                    ("manual", "Manual"),
                    ("backend_sdk", "Backend SDK"),
                    ("mcp", "MCP Server"),
                ],
                db_index=True,
                default="cli_sync",
                help_text="How this tool was registered (CLI sync, backend SDK, MCP, or manual)",
                max_length=20,
            ),
        ),
    ]
