# Generated by Django 5.2.9 on 2026-03-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_add_action_source_type_mcp_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("product", "name", "source_type")},
        ),
    ]
