# Generated by Django 5.2.9 on 2026-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_change_action_unique_to_product_name_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="identity_auto_link_by_email",
            field=models.BooleanField(
                default=False,
                help_text="Auto-link channel users to customer accounts by matching email addresses",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="identity_link_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL template for account linking. Use {code} placeholder. Example: https://app.acme.com/connect?code={code}",
                max_length=500,
            ),
        ),
    ]
