# Generated by Django 5.2.9 on 2026-03-18 18:14

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_product_identity_auto_link_by_email_and_more"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this agent (e.g., 'Support Bot', 'Email Assistant')",
                        max_length=255,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Web Widget"),
                            ("slack", "Slack"),
                            ("discord", "Discord"),
                            ("email", "Email"),
                            ("api", "API"),
                        ],
                        db_index=True,
                        help_text="Channel this agent serves",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this agent is accepting messages",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("neutral", "Neutral"),
                            ("concise", "Concise"),
                            ("formal", "Formal"),
                        ],
                        default="",
                        help_text="Tone of voice. Empty = use product default.",
                        max_length=50,
                    ),
                ),
                (
                    "guidance_override",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Channel-specific instructions appended to product agent_guidance. Use for channel-appropriate behavior: 'Keep responses under 3 sentences' for Slack, 'Use formal salutations' for email.",
                    ),
                ),
                (
                    "tool_allowlist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tool names this agent CAN use. Empty = all compatible tools.",
                    ),
                ),
                (
                    "tool_denylist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tool names this agent CANNOT use. Applied after allowlist.",
                    ),
                ),
                (
                    "max_response_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Max tokens for LLM response. Null = model default.",
                        null=True,
                    ),
                ),
                (
                    "include_sources",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include source citations in responses",
                    ),
                ),
                (
                    "include_suggested_followups",
                    models.BooleanField(
                        default=True, help_text="Whether to suggest follow-up questions"
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LLM model override. Empty = use product/org default.",
                        max_length=100,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True,
                        help_text="Temperature override for LLM. Null = use default.",
                        null=True,
                    ),
                ),
                (
                    "channel_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Channel-specific configuration (web embed settings, Slack formatting, etc.)",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Language override for this agent. Empty = use product default.",
                        max_length=10,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this agent belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "indexes": [
                    models.Index(
                        fields=["product", "channel", "is_active"],
                        name="agent_prod_chan_active_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "channel"),
                        name="unique_agent_per_product_channel",
                    )
                ],
            },
        ),
    ]
