# Generated by Django 5.2.9 on 2026-03-18 18:14

from django.db import migrations


def forwards(apps, schema_editor):
    """Create a default web Agent for every existing Product."""
    Product = apps.get_model('products', 'Product')
    Agent = apps.get_model('products', 'Agent')

    for product in Product.objects.all():
        if Agent.objects.filter(product=product, channel='web').exists():
            continue

        config = product.config or {}
        if not isinstance(config, dict):
            config = {}
        ai = config.get('ai', {})
        embed = config.get('embed', {})

        channel_config = {}
        if embed:
            channel_config.update(embed)
        for key in ['assistantName', 'welcomeMessage', 'inputPlaceholder',
                    'suggestedQuestions', 'openOnLoad']:
            if key in ai:
                channel_config[key] = ai[key]

        Agent.objects.create(
            organization=product.organization,
            product=product,
            name=ai.get('assistantName') or product.name,
            channel='web',
            is_active=ai.get('enabled', True),
            channel_config=channel_config,
        )


def backwards(apps, schema_editor):
    """Remove auto-created web agents."""
    Agent = apps.get_model('products', 'Agent')
    Agent.objects.filter(channel='web').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0031_add_agent_model"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
