# Generated by Django 5.2.9 on 2026-03-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0032_migrate_web_agents"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agent",
            name="unique_agent_per_product_channel",
        ),
    ]
