# Generated by Django 5.2.9 on 2026-03-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0018_knowledgesource_visibility"),
        ("products", "0033_remove_unique_agent_per_product_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="knowledge_scope",
            field=models.CharField(
                choices=[
                    ("all", "All Sources"),
                    ("all_internal", "All Internal"),
                    ("all_external", "All External"),
                    ("selected", "Selected Sources"),
                ],
                default="all",
                help_text="How this agent's knowledge access is scoped.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="knowledge_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge sources this agent can access (used when scope is 'selected').",
                related_name="agents",
                to="knowledge.knowledgesource",
            ),
        ),
    ]
