# Generated by Django 5.2.9 on 2026-03-20 17:27

import apps.products.models.agent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0035_backfill_web_agents"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Globally unique slug used as the SDK install key (e.g., 'acme')",
                max_length=100,
                null=True,
                unique=True,
                validators=[apps.products.models.agent.validate_slug],
            ),
        ),
    ]
