# Generated by Django 5.2.9 on 2026-03-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0037_backfill_agent_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="tool_allowlist",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="tool_denylist",
        ),
        migrations.AddField(
            model_name="agent",
            name="tool_allowances",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools included when scope is 'allowed'.",
                related_name="allowed_by_agents",
                to="products.action",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="tool_restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tools excluded when scope is 'restricted'.",
                related_name="restricted_by_agents",
                to="products.action",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="tool_scope",
            field=models.CharField(
                choices=[
                    ("all", "All Tools"),
                    ("all_server_side", "All Server-Side"),
                    ("all_client_side", "All Client-Side"),
                    ("restricted", "All With Restrictions"),
                    ("allowed", "Allowed Only"),
                    ("none", "No Tools"),
                ],
                default="all",
                help_text="How this agent's tool access is scoped.",
                max_length=20,
            ),
        ),
    ]
