# Generated by Django 5.2.9 on 2026-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_tool_scope_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tool_context_restrictions',
            field=models.JSONField(blank=True, default=dict, help_text='Map of tool_name -> list of allowed contexts (e.g. ["private"], ["public"], ["private", "team"]). Tools not listed are available in all contexts.'),
        ),
    ]
