# Generated by Django 5.2.9 on 2026-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0039_add_tool_context_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mcp_domain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Custom domain for MCP server access (e.g., 'mcp.acme.com'). Client CNAMEs this to ai.trypillar.com.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web", "Web Widget"),
                    ("slack", "Slack"),
                    ("discord", "Discord"),
                    ("email", "Email"),
                    ("api", "API"),
                    ("mcp", "MCP Server"),
                ],
                db_index=True,
                help_text="Channel this agent serves",
                max_length=20,
            ),
        ),
    ]
