# Generated by Django 5.2.9 on 2026-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0041_backfill_mcp_agents"),
        ("tools", "0002_alter_mcptoolsource_auth_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mcp_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="External MCP servers whose tools this agent can use.",
                related_name="agents",
                to="tools.mcptoolsource",
            ),
        ),
    ]
