# Generated by Django 5.2.9 on 2026-03-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0042_composable_mcp_sources"),
        ("tools", "0008_openapi_tool_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="openapi_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="OpenAPI specs whose operations this agent can call directly.",
                related_name="agents",
                to="tools.openapitoolsource",
            ),
        ),
    ]
