# Generated by Django 5.2.9 on 2026-03-24 18:05

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


def copy_implicit_m2m_to_through_table(apps, schema_editor):
    """Copy rows from the implicit junction table into the new through table."""
    AgentOpenAPISource = apps.get_model("products", "AgentOpenAPISource")
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT agent_id, openapitoolsource_id "
            "FROM products_agent_openapi_sources"
        )
        rows = cursor.fetchall()

    objs = [
        AgentOpenAPISource(
            agent_id=agent_id,
            openapi_source_id=source_id,
            operation_scope="all",
        )
        for agent_id, source_id in rows
    ]
    if objs:
        AgentOpenAPISource.objects.using(db_alias).bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0043_agent_openapi_sources"),
        ("tools", "0014_openapitoolsource_confirmation_default_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentOpenAPISource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_scope",
                    models.CharField(
                        choices=[
                            ("all", "All Operations"),
                            ("selected", "Selected Operations"),
                        ],
                        default="all",
                        help_text="Whether all operations or only selected ones are available.",
                        max_length=20,
                    ),
                ),
                (
                    "selected_operation_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of operation_id strings to include (only used when scope is 'selected').",
                    ),
                ),
                (
                    "confirmation_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of operation_id -> bool. True = require confirmation, False = skip confirmation. Missing = use source default.",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_openapi_configs",
                        to="products.agent",
                    ),
                ),
                (
                    "openapi_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configs",
                        to="tools.openapitoolsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent OpenAPI Source Config",
                "verbose_name_plural": "Agent OpenAPI Source Configs",
            },
        ),
        migrations.RunPython(
            copy_implicit_m2m_to_through_table,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="agent",
            name="openapi_sources",
        ),
        migrations.AddField(
            model_name="agent",
            name="openapi_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="OpenAPI specs whose operations this agent can call directly.",
                related_name="agents",
                through="products.AgentOpenAPISource",
                to="tools.openapitoolsource",
            ),
        ),
        migrations.AddIndex(
            model_name="agentopenapisource",
            index=models.Index(fields=["agent"], name="agentopenapi_agent_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentopenapisource",
            constraint=models.UniqueConstraint(
                fields=("agent", "openapi_source"), name="agent_openapi_src_uniq"
            ),
        ),
    ]
