# Generated by Django 5.2.9 on 2026-03-24 18:28

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


def convert_json_to_overrides(apps, schema_editor):
    """Convert existing JSONField data into AgentOpenAPIOperationOverride rows.

    For each AgentOpenAPISource:
    - If operation_scope='selected', create overrides with is_enabled=False
      for operations NOT in selected_operation_ids.
    - For each entry in confirmation_overrides, create an override row.
    """
    AgentOpenAPISource = apps.get_model("products", "AgentOpenAPISource")
    AgentOpenAPIOperationOverride = apps.get_model("products", "AgentOpenAPIOperationOverride")
    OpenAPIToolSource = apps.get_model("tools", "OpenAPIToolSource")

    for cfg in AgentOpenAPISource.objects.select_related("openapi_source").all():
        overrides_to_create = {}
        source = cfg.openapi_source
        all_op_ids = {
            op.get("operation_id")
            for op in (source.discovered_operations or [])
            if op.get("operation_id")
        }

        if cfg.operation_scope == "selected":
            selected = set(cfg.selected_operation_ids or [])
            for op_id in all_op_ids:
                if op_id not in selected:
                    overrides_to_create[op_id] = {"is_enabled": False}

        for op_id, requires_conf in (cfg.confirmation_overrides or {}).items():
            if op_id in overrides_to_create:
                overrides_to_create[op_id]["requires_confirmation"] = requires_conf
            else:
                overrides_to_create[op_id] = {"requires_confirmation": requires_conf}

        if overrides_to_create:
            AgentOpenAPIOperationOverride.objects.bulk_create([
                AgentOpenAPIOperationOverride(
                    agent_openapi_source=cfg,
                    operation_id=op_id,
                    is_enabled=vals.get("is_enabled"),
                    requires_confirmation=vals.get("requires_confirmation"),
                )
                for op_id, vals in overrides_to_create.items()
            ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0044_agentopenapisource_alter_agent_openapi_sources_and_more"),
        ("tools", "0017_add_openapi_operation_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentOpenAPIOperationOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_id", models.CharField(max_length=255)),
                ("is_enabled", models.BooleanField(blank=True, null=True)),
                ("requires_confirmation", models.BooleanField(blank=True, null=True)),
                (
                    "agent_openapi_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_overrides",
                        to="products.agentopenapisource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent OpenAPI Operation Override",
                "verbose_name_plural": "Agent OpenAPI Operation Overrides",
                "indexes": [
                    models.Index(
                        fields=["agent_openapi_source"],
                        name="agentopapi_override_src_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent_openapi_source", "operation_id"),
                        name="agent_openapi_op_override_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(
            convert_json_to_overrides,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="agentopenapisource",
            name="confirmation_overrides",
        ),
        migrations.RemoveField(
            model_name="agentopenapisource",
            name="operation_scope",
        ),
        migrations.RemoveField(
            model_name="agentopenapisource",
            name="selected_operation_ids",
        ),
    ]
