# Generated by Django 5.2.9 on 2026-03-25 03:45

import apps.products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0046_mcp_through_tables_and_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cf_custom_hostname_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cloudflare Custom Hostname ID for mcp_domain",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="mcp_domain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Custom domain for MCP server access (e.g., 'mcp.acme.com'). Client CNAMEs this to mcp-proxy.trypillar.com.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subdomain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique subdomain for this product (e.g., 'acme' for acme.trypillar.com)",
                max_length=50,
                null=True,
                unique=True,
                validators=[apps.products.models.product.validate_subdomain],
            ),
        ),
    ]
