# Generated by Django 5.2.9 on 2026-03-18 18:10

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0029_change_action_unique_to_product_name_source_type"),
        ("users", "0008_add_usage_alert_last_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        db_index=True,
                        help_text="Channel type: slack, discord, email, api",
                        max_length=20,
                    ),
                ),
                (
                    "channel_user_id",
                    models.CharField(
                        help_text="Channel-native user identifier (Slack user ID, Discord user ID, email address)",
                        max_length=255,
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Customer's internal user ID, as passed to Pillar.identify() on web",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="User's email (from channel profile or linking flow)",
                        max_length=254,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User's display name from the channel",
                        max_length=255,
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this mapping was created"
                    ),
                ),
                (
                    "linked_via",
                    models.CharField(
                        default="manual",
                        help_text="How the link was created: slash_command, api, auto_email, dashboard",
                        max_length=50,
                    ),
                ),
                (
                    "linked_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who initiated the link (admin user ID or 'self')",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this mapping is active (False = revoked)",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When this mapping was revoked", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this mapping belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_mappings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Mapping",
                "verbose_name_plural": "Identity Mappings",
                "indexes": [
                    models.Index(
                        fields=["product", "channel", "channel_user_id"],
                        name="idmap_prod_chan_uid_idx",
                    ),
                    models.Index(
                        fields=["product", "external_user_id"],
                        name="idmap_prod_extuid_idx",
                    ),
                    models.Index(
                        fields=["product", "channel", "is_active"],
                        name="idmap_prod_chan_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("product", "channel", "channel_user_id"),
                        name="idmap_active_chan_user_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LinkCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="The one-time linking code (alphanumeric, URL-safe)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("channel_user_id", models.CharField(max_length=255)),
                (
                    "channel_display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "channel_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this code expires (default: 10 minutes after creation)",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this code has been redeemed"
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "used_by_external_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The external_user_id that redeemed this code",
                        max_length=255,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="users.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_codes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Code",
                "verbose_name_plural": "Link Codes",
                "indexes": [
                    models.Index(
                        fields=["product", "channel", "channel_user_id"],
                        name="linkcode_prod_chan_uid_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"],
                        name="linkcode_expires_used_idx",
                    ),
                ],
            },
        ),
    ]
